# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Wt Bh Village Games
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import groupbykey as groupbykey
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_ext_bahari_hai.tasks import (
    assemble_dashboard_widgets as assemble_dashboard_widgets,
)
from ecoscope_workflows_ext_bahari_hai.tasks import clean_dataframe as clean_dataframe
from ecoscope_workflows_ext_bahari_hai.tasks import draw_arrests_map as draw_arrests_map
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_illegal_events_map as draw_illegal_events_map,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_illegal_fishing_map as draw_illegal_fishing_map,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_mangrove_logging_map as draw_mangrove_logging_map,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_poaching_map as draw_poaching_map,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    get_generation_date as get_generation_date,
)
from ecoscope_workflows_ext_bahari_hai.tasks import get_report_year as get_report_year
from ecoscope_workflows_ext_bh_village_games.tasks import (
    draw_activity_leaderboard as draw_activity_leaderboard,
)
from ecoscope_workflows_ext_bh_village_games.tasks import (
    draw_all_villages_icon_bar as draw_all_villages_icon_bar,
)
from ecoscope_workflows_ext_bh_village_games.tasks import (
    draw_community_feedback_table as draw_community_feedback_table,
)
from ecoscope_workflows_ext_bh_village_games.tasks import (
    draw_monthly_heatmap as draw_monthly_heatmap,
)
from ecoscope_workflows_ext_bh_village_games.tasks import (
    draw_village_donut_chart as draw_village_donut_chart,
)
from ecoscope_workflows_ext_bh_village_games.tasks import (
    draw_village_icon_bar as draw_village_icon_bar,
)
from ecoscope_workflows_ext_bh_village_games.tasks import (
    render_vg_report as render_vg_report,
)
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_ste.tasks import get_file_path as get_file_path

# %% [markdown]
# ## Workflow Details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Time Range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
    time_format=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .partial(**time_range_params)
    .call()
)


# %% [markdown]
# ## CSV input from CSV

# %%
# parameters

csv_input_params = dict(
    input_method=...,
)

# %%
# call the task


csv_input = (
    get_file_path.set_task_instance_id("csv_input")
    .handle_errors()
    .with_tracing()
    .partial(output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"], **csv_input_params)
    .call()
)


# %% [markdown]
# ## Load data

# %%
# parameters

load_data_params = dict()

# %%
# call the task


load_data = (
    load_df.set_task_instance_id("load_data")
    .handle_errors()
    .with_tracing()
    .partial(
        file_path=csv_input,
        layer="landDx_polygons",
        deserialize_json=False,
        **load_data_params,
    )
    .call()
)


# %% [markdown]
# ## Icons directory

# %%
# parameters

icons_input_params = dict(
    input_method=...,
)

# %%
# call the task


icons_input = (
    get_file_path.set_task_instance_id("icons_input")
    .handle_errors()
    .with_tracing()
    .partial(output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"], **icons_input_params)
    .call()
)


# %% [markdown]
# ## Marine layers path

# %%
# parameters

marine_layers_input_params = dict(
    input_method=...,
)

# %%
# call the task


marine_layers_input = (
    get_file_path.set_task_instance_id("marine_layers_input")
    .handle_errors()
    .with_tracing()
    .partial(
        output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **marine_layers_input_params,
    )
    .call()
)


# %% [markdown]
# ## Report template

# %%
# parameters

report_template_input_params = dict(
    input_method=...,
)

# %%
# call the task


report_template_input = (
    get_file_path.set_task_instance_id("report_template_input")
    .handle_errors()
    .with_tracing()
    .partial(
        output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **report_template_input_params,
    )
    .call()
)


# %% [markdown]
# ## Clean patrol data

# %%
# parameters

clean_data_params = dict()

# %%
# call the task


clean_data = (
    clean_dataframe.set_task_instance_id("clean_data")
    .handle_errors()
    .with_tracing()
    .partial(
        data=load_data,
        date_columns=["Patrol Start Date", "Waypoint Date"],
        date_format="%d-%b-%y",
        groupby_period=["Year", "Quarter"],
        numeric_columns=["X", "Y"],
        drop_duplicates=False,
        **clean_data_params,
    )
    .call()
)


# %% [markdown]
# ## Yearly groupers

# %%
# parameters

yearly_groupers_params = dict()

# %%
# call the task


yearly_groupers = (
    set_groupers.set_task_instance_id("yearly_groupers")
    .handle_errors()
    .with_tracing()
    .partial(groupers=[{"index_name": "Year"}], **yearly_groupers_params)
    .call()
)


# %% [markdown]
# ## Quarterly groupers

# %%
# parameters

quarterly_groupers_params = dict()

# %%
# call the task


quarterly_groupers = (
    set_groupers.set_task_instance_id("quarterly_groupers")
    .handle_errors()
    .with_tracing()
    .partial(groupers=[{"index_name": "Quarter"}], **quarterly_groupers_params)
    .call()
)


# %% [markdown]
# ## Split by year

# %%
# parameters

split_yearly_params = dict()

# %%
# call the task


split_yearly = (
    split_groups.set_task_instance_id("split_yearly")
    .handle_errors()
    .with_tracing()
    .partial(df=clean_data, groupers=yearly_groupers, **split_yearly_params)
    .call()
)


# %% [markdown]
# ## Split by quarter

# %%
# parameters

split_quarterly_params = dict()

# %%
# call the task


split_quarterly = (
    split_groups.set_task_instance_id("split_quarterly")
    .handle_errors()
    .with_tracing()
    .partial(df=clean_data, groupers=quarterly_groupers, **split_quarterly_params)
    .call()
)


# %% [markdown]
# ## Feedback table - poaching

# %%
# parameters

tbl_poaching_params = dict()

# %%
# call the task


tbl_poaching = (
    draw_community_feedback_table.set_task_instance_id("tbl_poaching")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        activity_key="poaching",
        icons_dir=icons_input,
        station_column="Station",
        village_column="Village",
        low_threshold=12,
        high_threshold=30,
        **tbl_poaching_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_yearly)
)


# %% [markdown]
# ## Persist feedback - poaching

# %%
# parameters

persist_tbl_poaching_params = dict(
    filename=...,
)

# %%
# call the task


persist_tbl_poaching = (
    persist_text.set_task_instance_id("persist_tbl_poaching")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="feedback_poaching",
        **persist_tbl_poaching_params,
    )
    .mapvalues(argnames=["text"], argvalues=tbl_poaching)
)


# %% [markdown]
# ## poaching table png

# %%
# parameters

png_tbl_poaching_params = dict()

# %%
# call the task


png_tbl_poaching = (
    html_to_png.set_task_instance_id("png_tbl_poaching")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_tbl_poaching_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_tbl_poaching)
)


# %% [markdown]
# ## Widget feedback - poaching

# %%
# parameters

widget_tbl_poaching_params = dict(
    view=...,
)

# %%
# call the task


widget_tbl_poaching = (
    create_plot_widget_single_view.set_task_instance_id("widget_tbl_poaching")
    .handle_errors()
    .with_tracing()
    .partial(title="Feedback: Poaching", **widget_tbl_poaching_params)
    .mapvalues(argnames=["data"], argvalues=persist_tbl_poaching)
)


# %% [markdown]
# ## Feedback table - mangrove

# %%
# parameters

tbl_mangrove_params = dict()

# %%
# call the task


tbl_mangrove = (
    draw_community_feedback_table.set_task_instance_id("tbl_mangrove")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        activity_key="mangrove logging",
        icons_dir=icons_input,
        station_column="Station",
        village_column="Village",
        low_threshold=12,
        high_threshold=30,
        **tbl_mangrove_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_yearly)
)


# %% [markdown]
# ## Persist feedback - mangrove

# %%
# parameters

persist_tbl_mangrove_params = dict(
    filename=...,
)

# %%
# call the task


persist_tbl_mangrove = (
    persist_text.set_task_instance_id("persist_tbl_mangrove")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="feedback_mangrove",
        **persist_tbl_mangrove_params,
    )
    .mapvalues(argnames=["text"], argvalues=tbl_mangrove)
)


# %% [markdown]
# ## mangrove table png

# %%
# parameters

png_tbl_mangrove_params = dict()

# %%
# call the task


png_tbl_mangrove = (
    html_to_png.set_task_instance_id("png_tbl_mangrove")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_tbl_mangrove_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_tbl_mangrove)
)


# %% [markdown]
# ## Widget feedback - mangrove

# %%
# parameters

widget_tbl_mangrove_params = dict(
    view=...,
)

# %%
# call the task


widget_tbl_mangrove = (
    create_plot_widget_single_view.set_task_instance_id("widget_tbl_mangrove")
    .handle_errors()
    .with_tracing()
    .partial(title="Feedback: Mangrove Logging", **widget_tbl_mangrove_params)
    .mapvalues(argnames=["data"], argvalues=persist_tbl_mangrove)
)


# %% [markdown]
# ## Feedback table - fishing

# %%
# parameters

tbl_fishing_params = dict()

# %%
# call the task


tbl_fishing = (
    draw_community_feedback_table.set_task_instance_id("tbl_fishing")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        activity_key="illegal fishing",
        icons_dir=icons_input,
        station_column="Station",
        village_column="Village",
        low_threshold=12,
        high_threshold=30,
        **tbl_fishing_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_yearly)
)


# %% [markdown]
# ## Persist feedback - fishing

# %%
# parameters

persist_tbl_fishing_params = dict(
    filename=...,
)

# %%
# call the task


persist_tbl_fishing = (
    persist_text.set_task_instance_id("persist_tbl_fishing")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="feedback_fishing",
        **persist_tbl_fishing_params,
    )
    .mapvalues(argnames=["text"], argvalues=tbl_fishing)
)


# %% [markdown]
# ## illegal fishing tbl png

# %%
# parameters

png_tbl_fishing_params = dict()

# %%
# call the task


png_tbl_fishing = (
    html_to_png.set_task_instance_id("png_tbl_fishing")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_tbl_fishing_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_tbl_fishing)
)


# %% [markdown]
# ## Widget feedback - fishing

# %%
# parameters

widget_tbl_fishing_params = dict(
    view=...,
)

# %%
# call the task


widget_tbl_fishing = (
    create_plot_widget_single_view.set_task_instance_id("widget_tbl_fishing")
    .handle_errors()
    .with_tracing()
    .partial(title="Feedback: Illegal Fishing", **widget_tbl_fishing_params)
    .mapvalues(argnames=["data"], argvalues=persist_tbl_fishing)
)


# %% [markdown]
# ## Feedback table - arrests

# %%
# parameters

tbl_arrests_params = dict()

# %%
# call the task


tbl_arrests = (
    draw_community_feedback_table.set_task_instance_id("tbl_arrests")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        activity_key="arrests",
        icons_dir=icons_input,
        station_column="Station",
        village_column="Village",
        low_threshold=12,
        high_threshold=30,
        **tbl_arrests_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_yearly)
)


# %% [markdown]
# ## Persist feedback - arrests

# %%
# parameters

persist_tbl_arrests_params = dict(
    filename=...,
)

# %%
# call the task


persist_tbl_arrests = (
    persist_text.set_task_instance_id("persist_tbl_arrests")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="feedback_arrests",
        **persist_tbl_arrests_params,
    )
    .mapvalues(argnames=["text"], argvalues=tbl_arrests)
)


# %% [markdown]
# ## arrests table png

# %%
# parameters

png_tbl_arrests_params = dict()

# %%
# call the task


png_tbl_arrests = (
    html_to_png.set_task_instance_id("png_tbl_arrests")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_tbl_arrests_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_tbl_arrests)
)


# %% [markdown]
# ## Widget feedback - arrests

# %%
# parameters

widget_tbl_arrests_params = dict(
    view=...,
)

# %%
# call the task


widget_tbl_arrests = (
    create_plot_widget_single_view.set_task_instance_id("widget_tbl_arrests")
    .handle_errors()
    .with_tracing()
    .partial(title="Feedback: Arrests", **widget_tbl_arrests_params)
    .mapvalues(argnames=["data"], argvalues=persist_tbl_arrests)
)


# %% [markdown]
# ## Feedback table - turtles

# %%
# parameters

tbl_turtles_params = dict()

# %%
# call the task


tbl_turtles = (
    draw_community_feedback_table.set_task_instance_id("tbl_turtles")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        activity_key="poached turtle sum",
        icons_dir=icons_input,
        station_column="Station",
        village_column="Village",
        low_threshold=12,
        high_threshold=30,
        **tbl_turtles_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_yearly)
)


# %% [markdown]
# ## Persist feedback - turtles

# %%
# parameters

persist_tbl_turtles_params = dict(
    filename=...,
)

# %%
# call the task


persist_tbl_turtles = (
    persist_text.set_task_instance_id("persist_tbl_turtles")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="feedback_turtles",
        **persist_tbl_turtles_params,
    )
    .mapvalues(argnames=["text"], argvalues=tbl_turtles)
)


# %% [markdown]
# ## poached turtles table png

# %%
# parameters

png_tbl_turtles_params = dict()

# %%
# call the task


png_tbl_turtles = (
    html_to_png.set_task_instance_id("png_tbl_turtles")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_tbl_turtles_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_tbl_turtles)
)


# %% [markdown]
# ## Widget feedback - turtles

# %%
# parameters

widget_tbl_turtles_params = dict(
    view=...,
)

# %%
# call the task


widget_tbl_turtles = (
    create_plot_widget_single_view.set_task_instance_id("widget_tbl_turtles")
    .handle_errors()
    .with_tracing()
    .partial(title="Feedback: Poached Turtles", **widget_tbl_turtles_params)
    .mapvalues(argnames=["data"], argvalues=persist_tbl_turtles)
)


# %% [markdown]
# ## Monthly heatmap

# %%
# parameters

monthly_heatmap_params = dict()

# %%
# call the task


monthly_heatmap = (
    draw_monthly_heatmap.set_task_instance_id("monthly_heatmap")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village_column="Village",
        title_prefix="Monthly Distribution of Illegal Events by Village",
        **monthly_heatmap_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_yearly)
)


# %% [markdown]
# ## Persist monthly heatmap

# %%
# parameters

persist_heatmap_params = dict(
    filename=...,
)

# %%
# call the task


persist_heatmap = (
    persist_text.set_task_instance_id("persist_heatmap")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="monthly_heatmap",
        **persist_heatmap_params,
    )
    .mapvalues(argnames=["text"], argvalues=monthly_heatmap)
)


# %% [markdown]
# ## monthly heatmap png

# %%
# parameters

png_monthly_heatmap_params = dict()

# %%
# call the task


png_monthly_heatmap = (
    html_to_png.set_task_instance_id("png_monthly_heatmap")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_monthly_heatmap_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_heatmap)
)


# %% [markdown]
# ## Widget monthly heatmap

# %%
# parameters

widget_heatmap_params = dict(
    view=...,
)

# %%
# call the task


widget_heatmap = (
    create_plot_widget_single_view.set_task_instance_id("widget_heatmap")
    .handle_errors()
    .with_tracing()
    .partial(title="Monthly Illegal Events Heatmap", **widget_heatmap_params)
    .mapvalues(argnames=["data"], argvalues=persist_heatmap)
)


# %% [markdown]
# ## Donut - Darakasi to Watamu

# %%
# parameters

donut_v01_params = dict()

# %%
# call the task


donut_v01 = (
    draw_village_donut_chart.set_task_instance_id("donut_v01")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Darakasi to Watamu",
        village_column="Village",
        damaging_col="Damaging coral activity",
        **donut_v01_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_yearly)
)


# %% [markdown]
# ## Persist donut v01

# %%
# parameters

persist_donut_v01_params = dict(
    filename=...,
)

# %%
# call the task


persist_donut_v01 = (
    persist_text.set_task_instance_id("persist_donut_v01")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="donut_darakasi_watamu",
        **persist_donut_v01_params,
    )
    .mapvalues(argnames=["text"], argvalues=donut_v01)
)


# %% [markdown]
# ## Donut v01 png

# %%
# parameters

png_donut_v01_params = dict()

# %%
# call the task


png_donut_v01 = (
    html_to_png.set_task_instance_id("png_donut_v01")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_donut_v01_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_donut_v01)
)


# %% [markdown]
# ## Widget donut v01

# %%
# parameters

widget_donut_v01_params = dict(
    view=...,
)

# %%
# call the task


widget_donut_v01 = (
    create_plot_widget_single_view.set_task_instance_id("widget_donut_v01")
    .handle_errors()
    .with_tracing()
    .partial(title="Donut: Darakasi to Watamu", **widget_donut_v01_params)
    .mapvalues(argnames=["data"], argvalues=persist_donut_v01)
)


# %% [markdown]
# ## Donut - Dongokundu to Sita

# %%
# parameters

donut_v02_params = dict()

# %%
# call the task


donut_v02 = (
    draw_village_donut_chart.set_task_instance_id("donut_v02")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Dongokundu to Sita",
        village_column="Village",
        damaging_col="Damaging coral activity",
        **donut_v02_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_yearly)
)


# %% [markdown]
# ## Persist donut v02

# %%
# parameters

persist_donut_v02_params = dict(
    filename=...,
)

# %%
# call the task


persist_donut_v02 = (
    persist_text.set_task_instance_id("persist_donut_v02")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="donut_dongokundu_sita",
        **persist_donut_v02_params,
    )
    .mapvalues(argnames=["text"], argvalues=donut_v02)
)


# %% [markdown]
# ## Donut v02 png

# %%
# parameters

png_donut_v02_params = dict()

# %%
# call the task


png_donut_v02 = (
    html_to_png.set_task_instance_id("png_donut_v02")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_donut_v02_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_donut_v02)
)


# %% [markdown]
# ## Widget donut v02

# %%
# parameters

widget_donut_v02_params = dict(
    view=...,
)

# %%
# call the task


widget_donut_v02 = (
    create_plot_widget_single_view.set_task_instance_id("widget_donut_v02")
    .handle_errors()
    .with_tracing()
    .partial(title="Donut: Dongokundu to Sita", **widget_donut_v02_params)
    .mapvalues(argnames=["data"], argvalues=persist_donut_v02)
)


# %% [markdown]
# ## Donut - Jacaranda to Kanani

# %%
# parameters

donut_v03_params = dict()

# %%
# call the task


donut_v03 = (
    draw_village_donut_chart.set_task_instance_id("donut_v03")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Jacaranda to Kanani",
        village_column="Village",
        damaging_col="Damaging coral activity",
        **donut_v03_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_yearly)
)


# %% [markdown]
# ## Persist donut v03

# %%
# parameters

persist_donut_v03_params = dict(
    filename=...,
)

# %%
# call the task


persist_donut_v03 = (
    persist_text.set_task_instance_id("persist_donut_v03")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="donut_jacaranda_kanani",
        **persist_donut_v03_params,
    )
    .mapvalues(argnames=["text"], argvalues=donut_v03)
)


# %% [markdown]
# ## Donut v03 png

# %%
# parameters

png_donut_v03_params = dict()

# %%
# call the task


png_donut_v03 = (
    html_to_png.set_task_instance_id("png_donut_v03")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_donut_v03_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_donut_v03)
)


# %% [markdown]
# ## Widget donut v03

# %%
# parameters

widget_donut_v03_params = dict(
    view=...,
)

# %%
# call the task


widget_donut_v03 = (
    create_plot_widget_single_view.set_task_instance_id("widget_donut_v03")
    .handle_errors()
    .with_tracing()
    .partial(title="Donut: Jacaranda to Kanani", **widget_donut_v03_params)
    .mapvalues(argnames=["data"], argvalues=persist_donut_v03)
)


# %% [markdown]
# ## Donut - Kanani to Darakasi

# %%
# parameters

donut_v04_params = dict()

# %%
# call the task


donut_v04 = (
    draw_village_donut_chart.set_task_instance_id("donut_v04")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Kanani to Darakasi",
        village_column="Village",
        damaging_col="Damaging coral activity",
        **donut_v04_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_yearly)
)


# %% [markdown]
# ## Persist donut v04

# %%
# parameters

persist_donut_v04_params = dict(
    filename=...,
)

# %%
# call the task


persist_donut_v04 = (
    persist_text.set_task_instance_id("persist_donut_v04")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="donut_kanani_darakasi",
        **persist_donut_v04_params,
    )
    .mapvalues(argnames=["text"], argvalues=donut_v04)
)


# %% [markdown]
# ## Donut v04 png

# %%
# parameters

png_donut_v04_params = dict()

# %%
# call the task


png_donut_v04 = (
    html_to_png.set_task_instance_id("png_donut_v04")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_donut_v04_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_donut_v04)
)


# %% [markdown]
# ## Widget donut v04

# %%
# parameters

widget_donut_v04_params = dict(
    view=...,
)

# %%
# call the task


widget_donut_v04 = (
    create_plot_widget_single_view.set_task_instance_id("widget_donut_v04")
    .handle_errors()
    .with_tracing()
    .partial(title="Donut: Kanani to Darakasi", **widget_donut_v04_params)
    .mapvalues(argnames=["data"], argvalues=persist_donut_v04)
)


# %% [markdown]
# ## Donut - Kivunjeni to Wesa

# %%
# parameters

donut_v05_params = dict()

# %%
# call the task


donut_v05 = (
    draw_village_donut_chart.set_task_instance_id("donut_v05")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Kivunjeni to Wesa",
        village_column="Village",
        damaging_col="Damaging coral activity",
        **donut_v05_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_yearly)
)


# %% [markdown]
# ## Persist donut v05

# %%
# parameters

persist_donut_v05_params = dict(
    filename=...,
)

# %%
# call the task


persist_donut_v05 = (
    persist_text.set_task_instance_id("persist_donut_v05")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="donut_kivunjeni_wesa",
        **persist_donut_v05_params,
    )
    .mapvalues(argnames=["text"], argvalues=donut_v05)
)


# %% [markdown]
# ## Donut v05 png

# %%
# parameters

png_donut_v05_params = dict()

# %%
# call the task


png_donut_v05 = (
    html_to_png.set_task_instance_id("png_donut_v05")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_donut_v05_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_donut_v05)
)


# %% [markdown]
# ## Widget donut v05

# %%
# parameters

widget_donut_v05_params = dict(
    view=...,
)

# %%
# call the task


widget_donut_v05 = (
    create_plot_widget_single_view.set_task_instance_id("widget_donut_v05")
    .handle_errors()
    .with_tracing()
    .partial(title="Donut: Kivunjeni to Wesa", **widget_donut_v05_params)
    .mapvalues(argnames=["data"], argvalues=persist_donut_v05)
)


# %% [markdown]
# ## Donut - Magangani to Mida

# %%
# parameters

donut_v06_params = dict()

# %%
# call the task


donut_v06 = (
    draw_village_donut_chart.set_task_instance_id("donut_v06")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Magangani to Mida",
        village_column="Village",
        damaging_col="Damaging coral activity",
        **donut_v06_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_yearly)
)


# %% [markdown]
# ## Persist donut v06

# %%
# parameters

persist_donut_v06_params = dict(
    filename=...,
)

# %%
# call the task


persist_donut_v06 = (
    persist_text.set_task_instance_id("persist_donut_v06")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="donut_magangani_mida",
        **persist_donut_v06_params,
    )
    .mapvalues(argnames=["text"], argvalues=donut_v06)
)


# %% [markdown]
# ## Donut v06 png

# %%
# parameters

png_donut_v06_params = dict()

# %%
# call the task


png_donut_v06 = (
    html_to_png.set_task_instance_id("png_donut_v06")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_donut_v06_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_donut_v06)
)


# %% [markdown]
# ## Widget donut v06

# %%
# parameters

widget_donut_v06_params = dict(
    view=...,
)

# %%
# call the task


widget_donut_v06 = (
    create_plot_widget_single_view.set_task_instance_id("widget_donut_v06")
    .handle_errors()
    .with_tracing()
    .partial(title="Donut: Magangani to Mida", **widget_donut_v06_params)
    .mapvalues(argnames=["data"], argvalues=persist_donut_v06)
)


# %% [markdown]
# ## Donut - Marafiki to Uyombo

# %%
# parameters

donut_v07_params = dict()

# %%
# call the task


donut_v07 = (
    draw_village_donut_chart.set_task_instance_id("donut_v07")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Marafiki to Uyombo",
        village_column="Village",
        damaging_col="Damaging coral activity",
        **donut_v07_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_yearly)
)


# %% [markdown]
# ## Persist donut v07

# %%
# parameters

persist_donut_v07_params = dict(
    filename=...,
)

# %%
# call the task


persist_donut_v07 = (
    persist_text.set_task_instance_id("persist_donut_v07")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="donut_marafiki_uyombo",
        **persist_donut_v07_params,
    )
    .mapvalues(argnames=["text"], argvalues=donut_v07)
)


# %% [markdown]
# ## Donut v07 png

# %%
# parameters

png_donut_v07_params = dict()

# %%
# call the task


png_donut_v07 = (
    html_to_png.set_task_instance_id("png_donut_v07")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_donut_v07_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_donut_v07)
)


# %% [markdown]
# ## Widget donut v07

# %%
# parameters

widget_donut_v07_params = dict(
    view=...,
)

# %%
# call the task


widget_donut_v07 = (
    create_plot_widget_single_view.set_task_instance_id("widget_donut_v07")
    .handle_errors()
    .with_tracing()
    .partial(title="Donut: Marafiki to Uyombo", **widget_donut_v07_params)
    .mapvalues(argnames=["data"], argvalues=persist_donut_v07)
)


# %% [markdown]
# ## Donut - Mawe Ya Kati to Jacaranda

# %%
# parameters

donut_v08_params = dict()

# %%
# call the task


donut_v08 = (
    draw_village_donut_chart.set_task_instance_id("donut_v08")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Mawe Ya Kati to Jacaranda",
        village_column="Village",
        damaging_col="Damaging coral activity",
        **donut_v08_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_yearly)
)


# %% [markdown]
# ## Persist donut v08

# %%
# parameters

persist_donut_v08_params = dict(
    filename=...,
)

# %%
# call the task


persist_donut_v08 = (
    persist_text.set_task_instance_id("persist_donut_v08")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="donut_mawe_jacaranda",
        **persist_donut_v08_params,
    )
    .mapvalues(argnames=["text"], argvalues=donut_v08)
)


# %% [markdown]
# ## Donut v08 png

# %%
# parameters

png_donut_v08_params = dict()

# %%
# call the task


png_donut_v08 = (
    html_to_png.set_task_instance_id("png_donut_v08")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_donut_v08_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_donut_v08)
)


# %% [markdown]
# ## Widget donut v08

# %%
# parameters

widget_donut_v08_params = dict(
    view=...,
)

# %%
# call the task


widget_donut_v08 = (
    create_plot_widget_single_view.set_task_instance_id("widget_donut_v08")
    .handle_errors()
    .with_tracing()
    .partial(title="Donut: Mawe Ya Kati to Jacaranda", **widget_donut_v08_params)
    .mapvalues(argnames=["data"], argvalues=persist_donut_v08)
)


# %% [markdown]
# ## Donut - Mid Mayungu to Mawe Ya Kati

# %%
# parameters

donut_v09_params = dict()

# %%
# call the task


donut_v09 = (
    draw_village_donut_chart.set_task_instance_id("donut_v09")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Mid Mayungu to Mawe Ya Kati",
        village_column="Village",
        damaging_col="Damaging coral activity",
        **donut_v09_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_yearly)
)


# %% [markdown]
# ## Persist donut v09

# %%
# parameters

persist_donut_v09_params = dict(
    filename=...,
)

# %%
# call the task


persist_donut_v09 = (
    persist_text.set_task_instance_id("persist_donut_v09")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="donut_mid_mayungu_mawe",
        **persist_donut_v09_params,
    )
    .mapvalues(argnames=["text"], argvalues=donut_v09)
)


# %% [markdown]
# ## Donut v09 png

# %%
# parameters

png_donut_v09_params = dict()

# %%
# call the task


png_donut_v09 = (
    html_to_png.set_task_instance_id("png_donut_v09")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_donut_v09_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_donut_v09)
)


# %% [markdown]
# ## Widget donut v09

# %%
# parameters

widget_donut_v09_params = dict(
    view=...,
)

# %%
# call the task


widget_donut_v09 = (
    create_plot_widget_single_view.set_task_instance_id("widget_donut_v09")
    .handle_errors()
    .with_tracing()
    .partial(title="Donut: Mid Mayungu to Mawe Ya Kati", **widget_donut_v09_params)
    .mapvalues(argnames=["data"], argvalues=persist_donut_v09)
)


# %% [markdown]
# ## Donut - Mida to Marafiki

# %%
# parameters

donut_v10_params = dict()

# %%
# call the task


donut_v10 = (
    draw_village_donut_chart.set_task_instance_id("donut_v10")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Mida to Marafiki",
        village_column="Village",
        damaging_col="Damaging coral activity",
        **donut_v10_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_yearly)
)


# %% [markdown]
# ## Persist donut v10

# %%
# parameters

persist_donut_v10_params = dict(
    filename=...,
)

# %%
# call the task


persist_donut_v10 = (
    persist_text.set_task_instance_id("persist_donut_v10")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="donut_mida_marafiki",
        **persist_donut_v10_params,
    )
    .mapvalues(argnames=["text"], argvalues=donut_v10)
)


# %% [markdown]
# ## Donut v10 png

# %%
# parameters

png_donut_v10_params = dict()

# %%
# call the task


png_donut_v10 = (
    html_to_png.set_task_instance_id("png_donut_v10")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_donut_v10_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_donut_v10)
)


# %% [markdown]
# ## Widget donut v10

# %%
# parameters

widget_donut_v10_params = dict(
    view=...,
)

# %%
# call the task


widget_donut_v10 = (
    create_plot_widget_single_view.set_task_instance_id("widget_donut_v10")
    .handle_errors()
    .with_tracing()
    .partial(title="Donut: Mida to Marafiki", **widget_donut_v10_params)
    .mapvalues(argnames=["data"], argvalues=persist_donut_v10)
)


# %% [markdown]
# ## Donut - Sita to Magangani

# %%
# parameters

donut_v11_params = dict()

# %%
# call the task


donut_v11 = (
    draw_village_donut_chart.set_task_instance_id("donut_v11")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Sita to Magangani",
        village_column="Village",
        damaging_col="Damaging coral activity",
        **donut_v11_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_yearly)
)


# %% [markdown]
# ## Persist donut v11

# %%
# parameters

persist_donut_v11_params = dict(
    filename=...,
)

# %%
# call the task


persist_donut_v11 = (
    persist_text.set_task_instance_id("persist_donut_v11")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="donut_sita_magangani",
        **persist_donut_v11_params,
    )
    .mapvalues(argnames=["text"], argvalues=donut_v11)
)


# %% [markdown]
# ## Donut v11 png

# %%
# parameters

png_donut_v11_params = dict()

# %%
# call the task


png_donut_v11 = (
    html_to_png.set_task_instance_id("png_donut_v11")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_donut_v11_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_donut_v11)
)


# %% [markdown]
# ## Widget donut v11

# %%
# parameters

widget_donut_v11_params = dict(
    view=...,
)

# %%
# call the task


widget_donut_v11 = (
    create_plot_widget_single_view.set_task_instance_id("widget_donut_v11")
    .handle_errors()
    .with_tracing()
    .partial(title="Donut: Sita to Magangani", **widget_donut_v11_params)
    .mapvalues(argnames=["data"], argvalues=persist_donut_v11)
)


# %% [markdown]
# ## Donut - Uyombo to Kivunjeni

# %%
# parameters

donut_v12_params = dict()

# %%
# call the task


donut_v12 = (
    draw_village_donut_chart.set_task_instance_id("donut_v12")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Uyombo to Kivunjeni",
        village_column="Village",
        damaging_col="Damaging coral activity",
        **donut_v12_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_yearly)
)


# %% [markdown]
# ## Persist donut v12

# %%
# parameters

persist_donut_v12_params = dict(
    filename=...,
)

# %%
# call the task


persist_donut_v12 = (
    persist_text.set_task_instance_id("persist_donut_v12")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="donut_uyombo_kivunjeni",
        **persist_donut_v12_params,
    )
    .mapvalues(argnames=["text"], argvalues=donut_v12)
)


# %% [markdown]
# ## Donut v12 png

# %%
# parameters

png_donut_v12_params = dict()

# %%
# call the task


png_donut_v12 = (
    html_to_png.set_task_instance_id("png_donut_v12")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_donut_v12_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_donut_v12)
)


# %% [markdown]
# ## Widget donut v12

# %%
# parameters

widget_donut_v12_params = dict(
    view=...,
)

# %%
# call the task


widget_donut_v12 = (
    create_plot_widget_single_view.set_task_instance_id("widget_donut_v12")
    .handle_errors()
    .with_tracing()
    .partial(title="Donut: Uyombo to Kivunjeni", **widget_donut_v12_params)
    .mapvalues(argnames=["data"], argvalues=persist_donut_v12)
)


# %% [markdown]
# ## Donut - Watamu to Dongokundu

# %%
# parameters

donut_v13_params = dict()

# %%
# call the task


donut_v13 = (
    draw_village_donut_chart.set_task_instance_id("donut_v13")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Watamu to Dongokundu",
        village_column="Village",
        damaging_col="Damaging coral activity",
        **donut_v13_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_yearly)
)


# %% [markdown]
# ## Persist donut v13

# %%
# parameters

persist_donut_v13_params = dict(
    filename=...,
)

# %%
# call the task


persist_donut_v13 = (
    persist_text.set_task_instance_id("persist_donut_v13")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="donut_watamu_dongokundu",
        **persist_donut_v13_params,
    )
    .mapvalues(argnames=["text"], argvalues=donut_v13)
)


# %% [markdown]
# ## Donut v13 png

# %%
# parameters

png_donut_v13_params = dict()

# %%
# call the task


png_donut_v13 = (
    html_to_png.set_task_instance_id("png_donut_v13")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_donut_v13_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_donut_v13)
)


# %% [markdown]
# ## Widget donut v13

# %%
# parameters

widget_donut_v13_params = dict(
    view=...,
)

# %%
# call the task


widget_donut_v13 = (
    create_plot_widget_single_view.set_task_instance_id("widget_donut_v13")
    .handle_errors()
    .with_tracing()
    .partial(title="Donut: Watamu to Dongokundu", **widget_donut_v13_params)
    .mapvalues(argnames=["data"], argvalues=persist_donut_v13)
)


# %% [markdown]
# ## Leaderboard - poaching

# %%
# parameters

lb_poaching_params = dict()

# %%
# call the task


lb_poaching = (
    draw_activity_leaderboard.set_task_instance_id("lb_poaching")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        activity_key="poaching",
        icons_dir=icons_input,
        station_column="Station",
        village_column="Village",
        no_mangrove_sectors=None,
        **lb_poaching_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_quarterly)
)


# %% [markdown]
# ## Persist lb poaching

# %%
# parameters

persist_lb_poaching_params = dict(
    filename=...,
)

# %%
# call the task


persist_lb_poaching = (
    persist_text.set_task_instance_id("persist_lb_poaching")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="lb_poaching",
        **persist_lb_poaching_params,
    )
    .mapvalues(argnames=["text"], argvalues=lb_poaching)
)


# %% [markdown]
# ## Poaching lb png

# %%
# parameters

png_lb_poaching_params = dict()

# %%
# call the task


png_lb_poaching = (
    html_to_png.set_task_instance_id("png_lb_poaching")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_lb_poaching_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_lb_poaching)
)


# %% [markdown]
# ## Widget lb poaching

# %%
# parameters

widget_lb_poaching_params = dict(
    view=...,
)

# %%
# call the task


widget_lb_poaching = (
    create_plot_widget_single_view.set_task_instance_id("widget_lb_poaching")
    .handle_errors()
    .with_tracing()
    .partial(title="Leaderboard: Poaching", **widget_lb_poaching_params)
    .mapvalues(argnames=["data"], argvalues=persist_lb_poaching)
)


# %% [markdown]
# ## Leaderboard - mangrove

# %%
# parameters

lb_mangrove_params = dict()

# %%
# call the task


lb_mangrove = (
    draw_activity_leaderboard.set_task_instance_id("lb_mangrove")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        activity_key="mangrove logging",
        icons_dir=icons_input,
        station_column="Station",
        village_column="Village",
        no_mangrove_sectors=[
            "Sector 2",
            "Sector 3",
            "Sector 4",
            "Sector 5",
            "Sector 13",
        ],
        **lb_mangrove_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_quarterly)
)


# %% [markdown]
# ## Persist lb mangrove

# %%
# parameters

persist_lb_mangrove_params = dict(
    filename=...,
)

# %%
# call the task


persist_lb_mangrove = (
    persist_text.set_task_instance_id("persist_lb_mangrove")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="lb_mangrove",
        **persist_lb_mangrove_params,
    )
    .mapvalues(argnames=["text"], argvalues=lb_mangrove)
)


# %% [markdown]
# ## Mangrove lb png

# %%
# parameters

png_lb_mangrove_params = dict()

# %%
# call the task


png_lb_mangrove = (
    html_to_png.set_task_instance_id("png_lb_mangrove")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_lb_mangrove_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_lb_mangrove)
)


# %% [markdown]
# ## Widget lb mangrove

# %%
# parameters

widget_lb_mangrove_params = dict(
    view=...,
)

# %%
# call the task


widget_lb_mangrove = (
    create_plot_widget_single_view.set_task_instance_id("widget_lb_mangrove")
    .handle_errors()
    .with_tracing()
    .partial(title="Leaderboard: Mangrove Logging", **widget_lb_mangrove_params)
    .mapvalues(argnames=["data"], argvalues=persist_lb_mangrove)
)


# %% [markdown]
# ## Leaderboard - fishing

# %%
# parameters

lb_fishing_params = dict()

# %%
# call the task


lb_fishing = (
    draw_activity_leaderboard.set_task_instance_id("lb_fishing")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        activity_key="illegal fishing",
        icons_dir=icons_input,
        station_column="Station",
        village_column="Village",
        no_mangrove_sectors=None,
        **lb_fishing_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_quarterly)
)


# %% [markdown]
# ## Persist lb fishing

# %%
# parameters

persist_lb_fishing_params = dict(
    filename=...,
)

# %%
# call the task


persist_lb_fishing = (
    persist_text.set_task_instance_id("persist_lb_fishing")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="lb_fishing",
        **persist_lb_fishing_params,
    )
    .mapvalues(argnames=["text"], argvalues=lb_fishing)
)


# %% [markdown]
# ## Fishing lb png

# %%
# parameters

png_lb_fishing_params = dict()

# %%
# call the task


png_lb_fishing = (
    html_to_png.set_task_instance_id("png_lb_fishing")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_lb_fishing_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_lb_fishing)
)


# %% [markdown]
# ## Widget lb fishing

# %%
# parameters

widget_lb_fishing_params = dict(
    view=...,
)

# %%
# call the task


widget_lb_fishing = (
    create_plot_widget_single_view.set_task_instance_id("widget_lb_fishing")
    .handle_errors()
    .with_tracing()
    .partial(title="Leaderboard: Illegal Fishing", **widget_lb_fishing_params)
    .mapvalues(argnames=["data"], argvalues=persist_lb_fishing)
)


# %% [markdown]
# ## Leaderboard - arrests

# %%
# parameters

lb_arrests_params = dict()

# %%
# call the task


lb_arrests = (
    draw_activity_leaderboard.set_task_instance_id("lb_arrests")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        activity_key="arrests",
        icons_dir=icons_input,
        station_column="Station",
        village_column="Village",
        no_mangrove_sectors=None,
        **lb_arrests_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_quarterly)
)


# %% [markdown]
# ## Persist lb arrests

# %%
# parameters

persist_lb_arrests_params = dict(
    filename=...,
)

# %%
# call the task


persist_lb_arrests = (
    persist_text.set_task_instance_id("persist_lb_arrests")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="lb_arrests",
        **persist_lb_arrests_params,
    )
    .mapvalues(argnames=["text"], argvalues=lb_arrests)
)


# %% [markdown]
# ## Arrests lb png

# %%
# parameters

png_lb_arrests_params = dict()

# %%
# call the task


png_lb_arrests = (
    html_to_png.set_task_instance_id("png_lb_arrests")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_lb_arrests_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_lb_arrests)
)


# %% [markdown]
# ## Widget lb arrests

# %%
# parameters

widget_lb_arrests_params = dict(
    view=...,
)

# %%
# call the task


widget_lb_arrests = (
    create_plot_widget_single_view.set_task_instance_id("widget_lb_arrests")
    .handle_errors()
    .with_tracing()
    .partial(title="Leaderboard: Arrests", **widget_lb_arrests_params)
    .mapvalues(argnames=["data"], argvalues=persist_lb_arrests)
)


# %% [markdown]
# ## Icon bar - Darakasi to Watamu

# %%
# parameters

ibar_v01_params = dict()

# %%
# call the task


ibar_v01 = (
    draw_village_icon_bar.set_task_instance_id("ibar_v01")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Darakasi to Watamu",
        icons_dir=icons_input,
        village_column="Village",
        icons_per_row=8,
        **ibar_v01_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_quarterly)
)


# %% [markdown]
# ## Persist ibar v01

# %%
# parameters

persist_ibar_v01_params = dict(
    filename=...,
)

# %%
# call the task


persist_ibar_v01 = (
    persist_text.set_task_instance_id("persist_ibar_v01")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="ibar_darakasi_watamu",
        **persist_ibar_v01_params,
    )
    .mapvalues(argnames=["text"], argvalues=ibar_v01)
)


# %% [markdown]
# ## Convert ibar v01 to PNG

# %%
# parameters

png_ibar_v01_params = dict()

# %%
# call the task


png_ibar_v01 = (
    html_to_png.set_task_instance_id("png_ibar_v01")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_ibar_v01_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v01)
)


# %% [markdown]
# ## Widget ibar v01

# %%
# parameters

widget_ibar_v01_params = dict(
    view=...,
)

# %%
# call the task


widget_ibar_v01 = (
    create_plot_widget_single_view.set_task_instance_id("widget_ibar_v01")
    .handle_errors()
    .with_tracing()
    .partial(title="Icon Bar: Darakasi to Watamu", **widget_ibar_v01_params)
    .mapvalues(argnames=["data"], argvalues=persist_ibar_v01)
)


# %% [markdown]
# ## Icon bar - Dongokundu to Sita

# %%
# parameters

ibar_v02_params = dict()

# %%
# call the task


ibar_v02 = (
    draw_village_icon_bar.set_task_instance_id("ibar_v02")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Dongokundu to Sita",
        icons_dir=icons_input,
        village_column="Village",
        icons_per_row=8,
        **ibar_v02_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_quarterly)
)


# %% [markdown]
# ## Persist ibar v02

# %%
# parameters

persist_ibar_v02_params = dict(
    filename=...,
)

# %%
# call the task


persist_ibar_v02 = (
    persist_text.set_task_instance_id("persist_ibar_v02")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="ibar_dongokundu_sita",
        **persist_ibar_v02_params,
    )
    .mapvalues(argnames=["text"], argvalues=ibar_v02)
)


# %% [markdown]
# ## Convert ibar v02 to PNG

# %%
# parameters

png_ibar_v02_params = dict()

# %%
# call the task


png_ibar_v02 = (
    html_to_png.set_task_instance_id("png_ibar_v02")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_ibar_v02_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v02)
)


# %% [markdown]
# ## Widget ibar v02

# %%
# parameters

widget_ibar_v02_params = dict(
    view=...,
)

# %%
# call the task


widget_ibar_v02 = (
    create_plot_widget_single_view.set_task_instance_id("widget_ibar_v02")
    .handle_errors()
    .with_tracing()
    .partial(title="Icon Bar: Dongokundu to Sita", **widget_ibar_v02_params)
    .mapvalues(argnames=["data"], argvalues=persist_ibar_v02)
)


# %% [markdown]
# ## Icon bar - Magangani to Mida

# %%
# parameters

ibar_v03_params = dict()

# %%
# call the task


ibar_v03 = (
    draw_village_icon_bar.set_task_instance_id("ibar_v03")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Magangani to Mida",
        icons_dir=icons_input,
        village_column="Village",
        icons_per_row=8,
        **ibar_v03_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_quarterly)
)


# %% [markdown]
# ## Persist ibar v03

# %%
# parameters

persist_ibar_v03_params = dict(
    filename=...,
)

# %%
# call the task


persist_ibar_v03 = (
    persist_text.set_task_instance_id("persist_ibar_v03")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="ibar_magangani_mida",
        **persist_ibar_v03_params,
    )
    .mapvalues(argnames=["text"], argvalues=ibar_v03)
)


# %% [markdown]
# ## Convert ibar v03 to PNG

# %%
# parameters

png_ibar_v03_params = dict()

# %%
# call the task


png_ibar_v03 = (
    html_to_png.set_task_instance_id("png_ibar_v03")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_ibar_v03_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v03)
)


# %% [markdown]
# ## Widget ibar v03

# %%
# parameters

widget_ibar_v03_params = dict(
    view=...,
)

# %%
# call the task


widget_ibar_v03 = (
    create_plot_widget_single_view.set_task_instance_id("widget_ibar_v03")
    .handle_errors()
    .with_tracing()
    .partial(title="Icon Bar: Magangani to Mida", **widget_ibar_v03_params)
    .mapvalues(argnames=["data"], argvalues=persist_ibar_v03)
)


# %% [markdown]
# ## Icon bar - Uyombo to Kivunjeni

# %%
# parameters

ibar_v04_params = dict()

# %%
# call the task


ibar_v04 = (
    draw_village_icon_bar.set_task_instance_id("ibar_v04")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Uyombo to Kivunjeni",
        icons_dir=icons_input,
        village_column="Village",
        icons_per_row=8,
        **ibar_v04_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_quarterly)
)


# %% [markdown]
# ## Persist ibar v04

# %%
# parameters

persist_ibar_v04_params = dict(
    filename=...,
)

# %%
# call the task


persist_ibar_v04 = (
    persist_text.set_task_instance_id("persist_ibar_v04")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="ibar_uyombo_kivunjeni",
        **persist_ibar_v04_params,
    )
    .mapvalues(argnames=["text"], argvalues=ibar_v04)
)


# %% [markdown]
# ## Convert ibar v04 to PNG

# %%
# parameters

png_ibar_v04_params = dict()

# %%
# call the task


png_ibar_v04 = (
    html_to_png.set_task_instance_id("png_ibar_v04")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_ibar_v04_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v04)
)


# %% [markdown]
# ## Widget ibar v04

# %%
# parameters

widget_ibar_v04_params = dict(
    view=...,
)

# %%
# call the task


widget_ibar_v04 = (
    create_plot_widget_single_view.set_task_instance_id("widget_ibar_v04")
    .handle_errors()
    .with_tracing()
    .partial(title="Icon Bar: Uyombo to Kivunjeni", **widget_ibar_v04_params)
    .mapvalues(argnames=["data"], argvalues=persist_ibar_v04)
)


# %% [markdown]
# ## Icon bar - Watamu to Dongokundu

# %%
# parameters

ibar_v05_params = dict()

# %%
# call the task


ibar_v05 = (
    draw_village_icon_bar.set_task_instance_id("ibar_v05")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Watamu to Dongokundu",
        icons_dir=icons_input,
        village_column="Village",
        icons_per_row=8,
        **ibar_v05_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_quarterly)
)


# %% [markdown]
# ## Persist ibar v05

# %%
# parameters

persist_ibar_v05_params = dict(
    filename=...,
)

# %%
# call the task


persist_ibar_v05 = (
    persist_text.set_task_instance_id("persist_ibar_v05")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="ibar_watamu_dongokundu",
        **persist_ibar_v05_params,
    )
    .mapvalues(argnames=["text"], argvalues=ibar_v05)
)


# %% [markdown]
# ## Convert ibar v05 to PNG

# %%
# parameters

png_ibar_v05_params = dict()

# %%
# call the task


png_ibar_v05 = (
    html_to_png.set_task_instance_id("png_ibar_v05")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_ibar_v05_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v05)
)


# %% [markdown]
# ## Widget ibar v05

# %%
# parameters

widget_ibar_v05_params = dict(
    view=...,
)

# %%
# call the task


widget_ibar_v05 = (
    create_plot_widget_single_view.set_task_instance_id("widget_ibar_v05")
    .handle_errors()
    .with_tracing()
    .partial(title="Icon Bar: Watamu to Dongokundu", **widget_ibar_v05_params)
    .mapvalues(argnames=["data"], argvalues=persist_ibar_v05)
)


# %% [markdown]
# ## Icon bar - Mida to Marafiki

# %%
# parameters

ibar_v06_params = dict()

# %%
# call the task


ibar_v06 = (
    draw_village_icon_bar.set_task_instance_id("ibar_v06")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Mida to Marafiki",
        icons_dir=icons_input,
        village_column="Village",
        icons_per_row=8,
        **ibar_v06_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_quarterly)
)


# %% [markdown]
# ## Persist ibar v06

# %%
# parameters

persist_ibar_v06_params = dict(
    filename=...,
)

# %%
# call the task


persist_ibar_v06 = (
    persist_text.set_task_instance_id("persist_ibar_v06")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="ibar_mida_marafiki",
        **persist_ibar_v06_params,
    )
    .mapvalues(argnames=["text"], argvalues=ibar_v06)
)


# %% [markdown]
# ## Convert ibar v06 to PNG

# %%
# parameters

png_ibar_v06_params = dict()

# %%
# call the task


png_ibar_v06 = (
    html_to_png.set_task_instance_id("png_ibar_v06")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_ibar_v06_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v06)
)


# %% [markdown]
# ## Widget ibar v06

# %%
# parameters

widget_ibar_v06_params = dict(
    view=...,
)

# %%
# call the task


widget_ibar_v06 = (
    create_plot_widget_single_view.set_task_instance_id("widget_ibar_v06")
    .handle_errors()
    .with_tracing()
    .partial(title="Icon Bar: Mida to Marafiki", **widget_ibar_v06_params)
    .mapvalues(argnames=["data"], argvalues=persist_ibar_v06)
)


# %% [markdown]
# ## Icon bar - Mawe Ya Kati to Jacaranda

# %%
# parameters

ibar_v07_params = dict()

# %%
# call the task


ibar_v07 = (
    draw_village_icon_bar.set_task_instance_id("ibar_v07")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Mawe Ya Kati to Jacaranda",
        icons_dir=icons_input,
        village_column="Village",
        icons_per_row=8,
        **ibar_v07_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_quarterly)
)


# %% [markdown]
# ## Persist ibar v07

# %%
# parameters

persist_ibar_v07_params = dict(
    filename=...,
)

# %%
# call the task


persist_ibar_v07 = (
    persist_text.set_task_instance_id("persist_ibar_v07")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="ibar_mawe_jacaranda",
        **persist_ibar_v07_params,
    )
    .mapvalues(argnames=["text"], argvalues=ibar_v07)
)


# %% [markdown]
# ## Convert ibar v07 to PNG

# %%
# parameters

png_ibar_v07_params = dict()

# %%
# call the task


png_ibar_v07 = (
    html_to_png.set_task_instance_id("png_ibar_v07")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_ibar_v07_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v07)
)


# %% [markdown]
# ## Widget ibar v07

# %%
# parameters

widget_ibar_v07_params = dict(
    view=...,
)

# %%
# call the task


widget_ibar_v07 = (
    create_plot_widget_single_view.set_task_instance_id("widget_ibar_v07")
    .handle_errors()
    .with_tracing()
    .partial(title="Icon Bar: Mawe Ya Kati to Jacaranda", **widget_ibar_v07_params)
    .mapvalues(argnames=["data"], argvalues=persist_ibar_v07)
)


# %% [markdown]
# ## Icon bar - Mid Mayungu to Mawe Ya Kati

# %%
# parameters

ibar_v08_params = dict()

# %%
# call the task


ibar_v08 = (
    draw_village_icon_bar.set_task_instance_id("ibar_v08")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Mid Mayungu to Mawe Ya Kati",
        icons_dir=icons_input,
        village_column="Village",
        icons_per_row=8,
        **ibar_v08_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_quarterly)
)


# %% [markdown]
# ## Persist ibar v08

# %%
# parameters

persist_ibar_v08_params = dict(
    filename=...,
)

# %%
# call the task


persist_ibar_v08 = (
    persist_text.set_task_instance_id("persist_ibar_v08")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="ibar_mid_mayungu_mawe",
        **persist_ibar_v08_params,
    )
    .mapvalues(argnames=["text"], argvalues=ibar_v08)
)


# %% [markdown]
# ## Convert ibar v08 to PNG

# %%
# parameters

png_ibar_v08_params = dict()

# %%
# call the task


png_ibar_v08 = (
    html_to_png.set_task_instance_id("png_ibar_v08")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_ibar_v08_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v08)
)


# %% [markdown]
# ## Widget ibar v08

# %%
# parameters

widget_ibar_v08_params = dict(
    view=...,
)

# %%
# call the task


widget_ibar_v08 = (
    create_plot_widget_single_view.set_task_instance_id("widget_ibar_v08")
    .handle_errors()
    .with_tracing()
    .partial(title="Icon Bar: Mid Mayungu to Mawe Ya Kati", **widget_ibar_v08_params)
    .mapvalues(argnames=["data"], argvalues=persist_ibar_v08)
)


# %% [markdown]
# ## Icon bar - Marafiki to Uyombo

# %%
# parameters

ibar_v09_params = dict()

# %%
# call the task


ibar_v09 = (
    draw_village_icon_bar.set_task_instance_id("ibar_v09")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Marafiki to Uyombo",
        icons_dir=icons_input,
        village_column="Village",
        icons_per_row=8,
        **ibar_v09_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_quarterly)
)


# %% [markdown]
# ## Persist ibar v09

# %%
# parameters

persist_ibar_v09_params = dict(
    filename=...,
)

# %%
# call the task


persist_ibar_v09 = (
    persist_text.set_task_instance_id("persist_ibar_v09")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="ibar_marafiki_uyombo",
        **persist_ibar_v09_params,
    )
    .mapvalues(argnames=["text"], argvalues=ibar_v09)
)


# %% [markdown]
# ## Convert ibar v09 to PNG

# %%
# parameters

png_ibar_v09_params = dict()

# %%
# call the task


png_ibar_v09 = (
    html_to_png.set_task_instance_id("png_ibar_v09")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_ibar_v09_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v09)
)


# %% [markdown]
# ## Widget ibar v09

# %%
# parameters

widget_ibar_v09_params = dict(
    view=...,
)

# %%
# call the task


widget_ibar_v09 = (
    create_plot_widget_single_view.set_task_instance_id("widget_ibar_v09")
    .handle_errors()
    .with_tracing()
    .partial(title="Icon Bar: Marafiki to Uyombo", **widget_ibar_v09_params)
    .mapvalues(argnames=["data"], argvalues=persist_ibar_v09)
)


# %% [markdown]
# ## Icon bar - Kivunjeni to Wesa

# %%
# parameters

ibar_v10_params = dict()

# %%
# call the task


ibar_v10 = (
    draw_village_icon_bar.set_task_instance_id("ibar_v10")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Kivunjeni to Wesa",
        icons_dir=icons_input,
        village_column="Village",
        icons_per_row=8,
        **ibar_v10_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_quarterly)
)


# %% [markdown]
# ## Persist ibar v10

# %%
# parameters

persist_ibar_v10_params = dict(
    filename=...,
)

# %%
# call the task


persist_ibar_v10 = (
    persist_text.set_task_instance_id("persist_ibar_v10")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="ibar_kivunjeni_wesa",
        **persist_ibar_v10_params,
    )
    .mapvalues(argnames=["text"], argvalues=ibar_v10)
)


# %% [markdown]
# ## Convert ibar v10 to PNG

# %%
# parameters

png_ibar_v10_params = dict()

# %%
# call the task


png_ibar_v10 = (
    html_to_png.set_task_instance_id("png_ibar_v10")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_ibar_v10_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v10)
)


# %% [markdown]
# ## Widget ibar v10

# %%
# parameters

widget_ibar_v10_params = dict(
    view=...,
)

# %%
# call the task


widget_ibar_v10 = (
    create_plot_widget_single_view.set_task_instance_id("widget_ibar_v10")
    .handle_errors()
    .with_tracing()
    .partial(title="Icon Bar: Kivunjeni to Wesa", **widget_ibar_v10_params)
    .mapvalues(argnames=["data"], argvalues=persist_ibar_v10)
)


# %% [markdown]
# ## Icon bar - Kanani to Darakasi

# %%
# parameters

ibar_v11_params = dict()

# %%
# call the task


ibar_v11 = (
    draw_village_icon_bar.set_task_instance_id("ibar_v11")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Kanani to Darakasi",
        icons_dir=icons_input,
        village_column="Village",
        icons_per_row=8,
        **ibar_v11_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_quarterly)
)


# %% [markdown]
# ## Persist ibar v11

# %%
# parameters

persist_ibar_v11_params = dict(
    filename=...,
)

# %%
# call the task


persist_ibar_v11 = (
    persist_text.set_task_instance_id("persist_ibar_v11")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="ibar_kanani_darakasi",
        **persist_ibar_v11_params,
    )
    .mapvalues(argnames=["text"], argvalues=ibar_v11)
)


# %% [markdown]
# ## Convert ibar v11 to PNG

# %%
# parameters

png_ibar_v11_params = dict()

# %%
# call the task


png_ibar_v11 = (
    html_to_png.set_task_instance_id("png_ibar_v11")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_ibar_v11_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v11)
)


# %% [markdown]
# ## Widget ibar v11

# %%
# parameters

widget_ibar_v11_params = dict(
    view=...,
)

# %%
# call the task


widget_ibar_v11 = (
    create_plot_widget_single_view.set_task_instance_id("widget_ibar_v11")
    .handle_errors()
    .with_tracing()
    .partial(title="Icon Bar: Kanani to Darakasi", **widget_ibar_v11_params)
    .mapvalues(argnames=["data"], argvalues=persist_ibar_v11)
)


# %% [markdown]
# ## Icon bar - Jacaranda to Kanani

# %%
# parameters

ibar_v12_params = dict()

# %%
# call the task


ibar_v12 = (
    draw_village_icon_bar.set_task_instance_id("ibar_v12")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Jacaranda to Kanani",
        icons_dir=icons_input,
        village_column="Village",
        icons_per_row=8,
        **ibar_v12_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_quarterly)
)


# %% [markdown]
# ## Persist ibar v12

# %%
# parameters

persist_ibar_v12_params = dict(
    filename=...,
)

# %%
# call the task


persist_ibar_v12 = (
    persist_text.set_task_instance_id("persist_ibar_v12")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="ibar_jacaranda_kanani",
        **persist_ibar_v12_params,
    )
    .mapvalues(argnames=["text"], argvalues=ibar_v12)
)


# %% [markdown]
# ## Convert ibar v12 to PNG

# %%
# parameters

png_ibar_v12_params = dict()

# %%
# call the task


png_ibar_v12 = (
    html_to_png.set_task_instance_id("png_ibar_v12")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_ibar_v12_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v12)
)


# %% [markdown]
# ## Widget ibar v12

# %%
# parameters

widget_ibar_v12_params = dict(
    view=...,
)

# %%
# call the task


widget_ibar_v12 = (
    create_plot_widget_single_view.set_task_instance_id("widget_ibar_v12")
    .handle_errors()
    .with_tracing()
    .partial(title="Icon Bar: Jacaranda to Kanani", **widget_ibar_v12_params)
    .mapvalues(argnames=["data"], argvalues=persist_ibar_v12)
)


# %% [markdown]
# ## Icon bar - Watamu to Dongokundu

# %%
# parameters

ibar_v13_params = dict()

# %%
# call the task


ibar_v13 = (
    draw_village_icon_bar.set_task_instance_id("ibar_v13")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        village="Watamu to Dongokundu",
        icons_dir=icons_input,
        village_column="Village",
        icons_per_row=8,
        **ibar_v13_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_quarterly)
)


# %% [markdown]
# ## Persist ibar v13

# %%
# parameters

persist_ibar_v13_params = dict(
    filename=...,
)

# %%
# call the task


persist_ibar_v13 = (
    persist_text.set_task_instance_id("persist_ibar_v13")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="ibar_watamu_dongokundu",
        **persist_ibar_v13_params,
    )
    .mapvalues(argnames=["text"], argvalues=ibar_v13)
)


# %% [markdown]
# ## Convert ibar v13 to PNG

# %%
# parameters

png_ibar_v13_params = dict()

# %%
# call the task


png_ibar_v13 = (
    html_to_png.set_task_instance_id("png_ibar_v13")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_ibar_v13_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v13)
)


# %% [markdown]
# ## Widget ibar v13

# %%
# parameters

widget_ibar_v13_params = dict(
    view=...,
)

# %%
# call the task


widget_ibar_v13 = (
    create_plot_widget_single_view.set_task_instance_id("widget_ibar_v13")
    .handle_errors()
    .with_tracing()
    .partial(title="Icon Bar: Watamu to Dongokundu", **widget_ibar_v13_params)
    .mapvalues(argnames=["data"], argvalues=persist_ibar_v13)
)


# %% [markdown]
# ## All-villages icon bar

# %%
# parameters

all_villages_bar_params = dict()

# %%
# call the task


all_villages_bar = (
    draw_all_villages_icon_bar.set_task_instance_id("all_villages_bar")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        icons_dir=icons_input,
        village_column="Village",
        icons_per_row=8,
        **all_villages_bar_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_quarterly)
)


# %% [markdown]
# ## Persist all-villages bar

# %%
# parameters

persist_all_villages_bar_params = dict(
    filename=...,
)

# %%
# call the task


persist_all_villages_bar = (
    persist_text.set_task_instance_id("persist_all_villages_bar")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="all_villages_icon_bar",
        **persist_all_villages_bar_params,
    )
    .mapvalues(argnames=["text"], argvalues=all_villages_bar)
)


# %% [markdown]
# ## Convert all-villages bar to PNG

# %%
# parameters

png_all_villages_bar_params = dict()

# %%
# call the task


png_all_villages_bar = (
    html_to_png.set_task_instance_id("png_all_villages_bar")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_all_villages_bar_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_all_villages_bar)
)


# %% [markdown]
# ## Widget all-villages bar

# %%
# parameters

widget_all_villages_bar_params = dict(
    view=...,
)

# %%
# call the task


widget_all_villages_bar = (
    create_plot_widget_single_view.set_task_instance_id("widget_all_villages_bar")
    .handle_errors()
    .with_tracing()
    .partial(title="All Villages Illegal Events", **widget_all_villages_bar_params)
    .mapvalues(argnames=["data"], argvalues=persist_all_villages_bar)
)


# %% [markdown]
# ## Split for maps

# %%
# parameters

split_maps_params = dict()

# %%
# call the task


split_maps = (
    split_groups.set_task_instance_id("split_maps")
    .handle_errors()
    .with_tracing()
    .partial(df=clean_data, groupers=yearly_groupers, **split_maps_params)
    .call()
)


# %% [markdown]
# ## Illegal events map

# %%
# parameters

illegal_events_map_params = dict()

# %%
# call the task


illegal_events_map = (
    draw_illegal_events_map.set_task_instance_id("illegal_events_map")
    .handle_errors()
    .with_tracing()
    .partial(
        groupers=yearly_groupers,
        marine_layers_path=marine_layers_input,
        widget_id="Illegal Events Map",
        **illegal_events_map_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_maps)
)


# %% [markdown]
# ## Persist illegal events map

# %%
# parameters

persist_ie_map_params = dict(
    filename=...,
)

# %%
# call the task


persist_ie_map = (
    persist_text.set_task_instance_id("persist_ie_map")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="illegal_events_map",
        **persist_ie_map_params,
    )
    .mapvalues(argnames=["text"], argvalues=illegal_events_map)
)


# %% [markdown]
# ## Convert illegal events map to PNG

# %%
# parameters

png_ie_map_params = dict()

# %%
# call the task


png_ie_map = (
    html_to_png.set_task_instance_id("png_ie_map")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_ie_map_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_ie_map)
)


# %% [markdown]
# ## Widget illegal events map

# %%
# parameters

widget_ie_map_params = dict(
    view=...,
)

# %%
# call the task


widget_ie_map = (
    create_map_widget_single_view.set_task_instance_id("widget_ie_map")
    .handle_errors()
    .with_tracing()
    .partial(title="Illegal Events Map", **widget_ie_map_params)
    .mapvalues(argnames=["data"], argvalues=persist_ie_map)
)


# %% [markdown]
# ## Poaching map

# %%
# parameters

poaching_map_params = dict()

# %%
# call the task


poaching_map = (
    draw_poaching_map.set_task_instance_id("poaching_map")
    .handle_errors()
    .with_tracing()
    .partial(
        groupers=yearly_groupers,
        marine_layers_path=marine_layers_input,
        widget_id="Poaching Hotspot Map",
        **poaching_map_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_maps)
)


# %% [markdown]
# ## Persist poaching map

# %%
# parameters

persist_poaching_map_params = dict(
    filename=...,
)

# %%
# call the task


persist_poaching_map = (
    persist_text.set_task_instance_id("persist_poaching_map")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="poaching_map",
        **persist_poaching_map_params,
    )
    .mapvalues(argnames=["text"], argvalues=poaching_map)
)


# %% [markdown]
# ## Convert poaching map to PNG

# %%
# parameters

png_poaching_map_params = dict()

# %%
# call the task


png_poaching_map = (
    html_to_png.set_task_instance_id("png_poaching_map")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_poaching_map_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_poaching_map)
)


# %% [markdown]
# ## Widget poaching map

# %%
# parameters

widget_poaching_map_params = dict(
    view=...,
)

# %%
# call the task


widget_poaching_map = (
    create_map_widget_single_view.set_task_instance_id("widget_poaching_map")
    .handle_errors()
    .with_tracing()
    .partial(title="Poaching Hotspot Map", **widget_poaching_map_params)
    .mapvalues(argnames=["data"], argvalues=persist_poaching_map)
)


# %% [markdown]
# ## Mangrove logging map

# %%
# parameters

mangrove_map_params = dict()

# %%
# call the task


mangrove_map = (
    draw_mangrove_logging_map.set_task_instance_id("mangrove_map")
    .handle_errors()
    .with_tracing()
    .partial(
        groupers=yearly_groupers,
        marine_layers_path=marine_layers_input,
        widget_id="Mangrove Logging Map",
        **mangrove_map_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_maps)
)


# %% [markdown]
# ## Persist mangrove map

# %%
# parameters

persist_mangrove_map_params = dict(
    filename=...,
)

# %%
# call the task


persist_mangrove_map = (
    persist_text.set_task_instance_id("persist_mangrove_map")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="mangrove_map",
        **persist_mangrove_map_params,
    )
    .mapvalues(argnames=["text"], argvalues=mangrove_map)
)


# %% [markdown]
# ## Convert mangrove map to PNG

# %%
# parameters

png_mangrove_map_params = dict()

# %%
# call the task


png_mangrove_map = (
    html_to_png.set_task_instance_id("png_mangrove_map")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_mangrove_map_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_mangrove_map)
)


# %% [markdown]
# ## Widget mangrove map

# %%
# parameters

widget_mangrove_map_params = dict(
    view=...,
)

# %%
# call the task


widget_mangrove_map = (
    create_map_widget_single_view.set_task_instance_id("widget_mangrove_map")
    .handle_errors()
    .with_tracing()
    .partial(title="Mangrove Logging Map", **widget_mangrove_map_params)
    .mapvalues(argnames=["data"], argvalues=persist_mangrove_map)
)


# %% [markdown]
# ## Illegal fishing map

# %%
# parameters

illegal_fishing_map_params = dict()

# %%
# call the task


illegal_fishing_map = (
    draw_illegal_fishing_map.set_task_instance_id("illegal_fishing_map")
    .handle_errors()
    .with_tracing()
    .partial(
        groupers=yearly_groupers,
        marine_layers_path=marine_layers_input,
        widget_id="Illegal Fishing Map",
        **illegal_fishing_map_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_maps)
)


# %% [markdown]
# ## Persist illegal fishing map

# %%
# parameters

persist_illegal_fishing_map_params = dict(
    filename=...,
)

# %%
# call the task


persist_illegal_fishing_map = (
    persist_text.set_task_instance_id("persist_illegal_fishing_map")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="illegal_fishing_map",
        **persist_illegal_fishing_map_params,
    )
    .mapvalues(argnames=["text"], argvalues=illegal_fishing_map)
)


# %% [markdown]
# ## Convert illegal fishing map to PNG

# %%
# parameters

png_illegal_fishing_map_params = dict()

# %%
# call the task


png_illegal_fishing_map = (
    html_to_png.set_task_instance_id("png_illegal_fishing_map")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_illegal_fishing_map_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_illegal_fishing_map)
)


# %% [markdown]
# ## Widget illegal fishing map

# %%
# parameters

widget_illegal_fishing_map_params = dict(
    view=...,
)

# %%
# call the task


widget_illegal_fishing_map = (
    create_map_widget_single_view.set_task_instance_id("widget_illegal_fishing_map")
    .handle_errors()
    .with_tracing()
    .partial(title="Illegal Fishing Map", **widget_illegal_fishing_map_params)
    .mapvalues(argnames=["data"], argvalues=persist_illegal_fishing_map)
)


# %% [markdown]
# ## Arrests map

# %%
# parameters

arrests_map_params = dict()

# %%
# call the task


arrests_map = (
    draw_arrests_map.set_task_instance_id("arrests_map")
    .handle_errors()
    .with_tracing()
    .partial(
        groupers=yearly_groupers,
        marine_layers_path=marine_layers_input,
        widget_id="Arrests Map",
        **arrests_map_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_maps)
)


# %% [markdown]
# ## Persist arrests map

# %%
# parameters

persist_arrests_map_params = dict(
    filename=...,
)

# %%
# call the task


persist_arrests_map = (
    persist_text.set_task_instance_id("persist_arrests_map")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="arrests_map",
        **persist_arrests_map_params,
    )
    .mapvalues(argnames=["text"], argvalues=arrests_map)
)


# %% [markdown]
# ## Convert arrests map to PNG

# %%
# parameters

png_arrests_map_params = dict()

# %%
# call the task


png_arrests_map = (
    html_to_png.set_task_instance_id("png_arrests_map")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_arrests_map_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_arrests_map)
)


# %% [markdown]
# ## Widget arrests map

# %%
# parameters

widget_arrests_map_params = dict(
    view=...,
)

# %%
# call the task


widget_arrests_map = (
    create_map_widget_single_view.set_task_instance_id("widget_arrests_map")
    .handle_errors()
    .with_tracing()
    .partial(title="Arrests Map", **widget_arrests_map_params)
    .mapvalues(argnames=["data"], argvalues=persist_arrests_map)
)


# %% [markdown]
# ## Get report year

# %%
# parameters

report_year_params = dict()

# %%
# call the task


report_year = (
    get_report_year.set_task_instance_id("report_year")
    .handle_errors()
    .with_tracing()
    .partial(df=clean_data, groupers=yearly_groupers, **report_year_params)
    .call()
)


# %% [markdown]
# ## Get report generation date

# %%
# parameters

report_generation_date_params = dict()

# %%
# call the task


report_generation_date = (
    get_generation_date.set_task_instance_id("report_generation_date")
    .handle_errors()
    .with_tracing()
    .partial(**report_generation_date_params)
    .call()
)


# %% [markdown]
# ## Render village games report

# %%
# parameters

render_village_games_report_params = dict()

# %%
# call the task


render_village_games_report = (
    render_vg_report.set_task_instance_id("render_village_games_report")
    .handle_errors()
    .with_tracing()
    .partial(
        template_path=report_template_input,
        output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        report_year=report_year,
        generation_date=report_generation_date,
        feedback_poaching_png=png_tbl_poaching,
        feedback_mangrove_png=png_tbl_mangrove,
        feedback_fishing_png=png_tbl_fishing,
        feedback_arrests_png=png_tbl_arrests,
        feedback_turtles_png=png_tbl_turtles,
        monthly_heatmap_png=png_monthly_heatmap,
        donut_darakasi_watamu_png=png_donut_v01,
        donut_dongokundu_sita_png=png_donut_v02,
        donut_jacaranda_kanani_png=png_donut_v03,
        donut_kanani_darakasi_png=png_donut_v04,
        donut_kivunjeni_wesa_png=png_donut_v05,
        donut_magangani_mida_png=png_donut_v06,
        donut_marafiki_uyombo_png=png_donut_v07,
        donut_mawe_jacaranda_png=png_donut_v08,
        donut_mid_mayungu_mawe_png=png_donut_v09,
        donut_mida_marafiki_png=png_donut_v10,
        donut_sita_magangani_png=png_donut_v11,
        donut_uyombo_kivunjeni_png=png_donut_v12,
        donut_watamu_dongokundu_png=png_donut_v13,
        lb_poaching_png=png_lb_poaching,
        lb_mangrove_png=png_lb_mangrove,
        lb_fishing_png=png_lb_fishing,
        lb_arrests_png=png_lb_arrests,
        ibar_darakasi_watamu_png=png_ibar_v01,
        ibar_dongokundu_sita_png=png_ibar_v02,
        ibar_magangani_mida_png=png_ibar_v03,
        ibar_uyombo_kivunjeni_png=png_ibar_v04,
        ibar_watamu_dongokundu_png=png_ibar_v05,
        ibar_mida_marafiki_png=png_ibar_v06,
        ibar_mawe_jacaranda_png=png_ibar_v07,
        ibar_mid_mayungu_mawe_png=png_ibar_v08,
        ibar_marafiki_uyombo_png=png_ibar_v09,
        ibar_kivunjeni_wesa_png=png_ibar_v10,
        ibar_kanani_darakasi_png=png_ibar_v11,
        ibar_jacaranda_kanani_png=png_ibar_v12,
        all_villages_icon_bar_png=png_all_villages_bar,
        illegal_events_map_png=png_ie_map,
        poaching_map_png=png_poaching_map,
        mangrove_map_png=png_mangrove_map,
        illegal_fishing_map_png=png_illegal_fishing_map,
        arrests_map_png=png_arrests_map,
        **render_village_games_report_params,
    )
    .call()
)


# %% [markdown]
# ## Merge yearly grouped widgets

# %%
# parameters

grouped_yearly_params = dict()

# %%
# call the task


grouped_yearly = (
    groupbykey.set_task_instance_id("grouped_yearly")
    .handle_errors()
    .with_tracing()
    .partial(
        iterables=[
            widget_tbl_poaching,
            widget_tbl_mangrove,
            widget_tbl_fishing,
            widget_tbl_arrests,
            widget_tbl_turtles,
            widget_heatmap,
            widget_donut_v01,
            widget_donut_v02,
            widget_donut_v03,
            widget_donut_v04,
            widget_donut_v05,
            widget_donut_v06,
            widget_donut_v07,
            widget_donut_v08,
            widget_donut_v09,
            widget_donut_v10,
            widget_donut_v11,
            widget_donut_v12,
            widget_donut_v13,
            widget_ie_map,
            widget_poaching_map,
            widget_mangrove_map,
            widget_illegal_fishing_map,
            widget_arrests_map,
        ],
        **grouped_yearly_params,
    )
    .call()
)


# %% [markdown]
# ## Merge quarterly grouped widgets

# %%
# parameters

grouped_quarterly_params = dict()

# %%
# call the task


grouped_quarterly = (
    groupbykey.set_task_instance_id("grouped_quarterly")
    .handle_errors()
    .with_tracing()
    .partial(
        iterables=[
            widget_lb_poaching,
            widget_lb_mangrove,
            widget_lb_fishing,
            widget_lb_arrests,
            widget_ibar_v01,
            widget_ibar_v02,
            widget_ibar_v03,
            widget_ibar_v04,
            widget_ibar_v05,
            widget_ibar_v06,
            widget_ibar_v07,
            widget_ibar_v08,
            widget_ibar_v09,
            widget_ibar_v10,
            widget_ibar_v11,
            widget_ibar_v12,
            widget_ibar_v13,
            widget_all_villages_bar,
        ],
        **grouped_quarterly_params,
    )
    .call()
)


# %% [markdown]
# ## Assemble dashboard widgets

# %%
# parameters

dashboard_widgets_params = dict()

# %%
# call the task


dashboard_widgets = (
    assemble_dashboard_widgets.set_task_instance_id("dashboard_widgets")
    .handle_errors()
    .with_tracing()
    .partial(
        single_view_widgets=[], keyed_widgets=grouped_yearly, **dashboard_widgets_params
    )
    .call()
)


# %% [markdown]
# ## Village Games Dashboard

# %%
# parameters

vg_dashboard_params = dict(
    warning=...,
)

# %%
# call the task


vg_dashboard = (
    gather_dashboard.set_task_instance_id("vg_dashboard")
    .handle_errors()
    .with_tracing()
    .partial(
        details=workflow_details,
        groupers=yearly_groupers,
        widgets=dashboard_widgets,
        time_range=time_range,
        **vg_dashboard_params,
    )
    .call()
)
