# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import groupbykey as groupbykey
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_ext_bahari_hai.tasks import (
    assemble_dashboard_widgets as assemble_dashboard_widgets,
)
from ecoscope_workflows_ext_bahari_hai.tasks import clean_dataframe as clean_dataframe
from ecoscope_workflows_ext_bahari_hai.tasks import draw_arrests_map as draw_arrests_map
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_illegal_events_map as draw_illegal_events_map,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_illegal_fishing_map as draw_illegal_fishing_map,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_mangrove_logging_map as draw_mangrove_logging_map,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_poaching_map as draw_poaching_map,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    get_generation_date as get_generation_date,
)
from ecoscope_workflows_ext_bahari_hai.tasks import get_report_year as get_report_year
from ecoscope_workflows_ext_bh_village_games.tasks import (
    draw_activity_leaderboard as draw_activity_leaderboard,
)
from ecoscope_workflows_ext_bh_village_games.tasks import (
    draw_all_villages_icon_bar as draw_all_villages_icon_bar,
)
from ecoscope_workflows_ext_bh_village_games.tasks import (
    draw_community_feedback_table as draw_community_feedback_table,
)
from ecoscope_workflows_ext_bh_village_games.tasks import (
    draw_monthly_heatmap as draw_monthly_heatmap,
)
from ecoscope_workflows_ext_bh_village_games.tasks import (
    draw_village_donut_chart as draw_village_donut_chart,
)
from ecoscope_workflows_ext_bh_village_games.tasks import (
    draw_village_icon_bar as draw_village_icon_bar,
)
from ecoscope_workflows_ext_bh_village_games.tasks import (
    render_vg_report as render_vg_report,
)
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_ste.tasks import (
    fetch_and_persist_file as fetch_and_persist_file,
)

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("time_range") or {}))
        .call()
    )

    csv_input = (
        fetch_and_persist_file.validate()
        .set_task_instance_id("csv_input")
        .handle_errors()
        .with_tracing()
        .partial(
            url="https://raw.githubusercontent.com/wildlife-dynamics/wt-bh-village-games/ae1f5bfb247c0bdde169caaaaf4e5c96cafb6b75/data/patrol_findings_with_village.csv",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            unzip=False,
            retries=3,
            overwrite_existing=False,
            **(params_dict.get("csv_input") or {}),
        )
        .call()
    )

    load_data = (
        load_df.validate()
        .set_task_instance_id("load_data")
        .handle_errors()
        .with_tracing()
        .partial(
            file_path=csv_input,
            layer="landDx_polygons",
            deserialize_json=False,
            **(params_dict.get("load_data") or {}),
        )
        .call()
    )

    icons_input = (
        fetch_and_persist_file.validate()
        .set_task_instance_id("icons_input")
        .handle_errors()
        .with_tracing()
        .partial(
            url="https://drive.google.com/uc?export=download&id=1jwJiY4Uayu2RNQ2Hq411ba-M6112OKTC",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            unzip=True,
            retries=3,
            overwrite_existing=False,
            **(params_dict.get("icons_input") or {}),
        )
        .call()
    )

    marine_layers_input = (
        fetch_and_persist_file.validate()
        .set_task_instance_id("marine_layers_input")
        .handle_errors()
        .with_tracing()
        .partial(
            url="https://drive.google.com/uc?export=download&id=1pNu0xS9lMN-O4SPpSiBihYcUTOGwN5_H",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            unzip=True,
            retries=3,
            overwrite_existing=False,
            **(params_dict.get("marine_layers_input") or {}),
        )
        .call()
    )

    report_template_input = (
        fetch_and_persist_file.validate()
        .set_task_instance_id("report_template_input")
        .handle_errors()
        .with_tracing()
        .partial(
            url="https://raw.githubusercontent.com/wildlife-dynamics/wt-bh-village-games/ae1f5bfb247c0bdde169caaaaf4e5c96cafb6b75/data/bahari_hai_village_games_report_template.docx",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            unzip=False,
            retries=3,
            overwrite_existing=False,
            **(params_dict.get("report_template_input") or {}),
        )
        .call()
    )

    clean_data = (
        clean_dataframe.validate()
        .set_task_instance_id("clean_data")
        .handle_errors()
        .with_tracing()
        .partial(
            data=load_data,
            date_columns=["Patrol Start Date", "Waypoint Date"],
            date_format="%d-%b-%y",
            groupby_period=["Year", "Quarter"],
            numeric_columns=["X", "Y"],
            drop_duplicates=False,
            **(params_dict.get("clean_data") or {}),
        )
        .call()
    )

    yearly_groupers = (
        set_groupers.validate()
        .set_task_instance_id("yearly_groupers")
        .handle_errors()
        .with_tracing()
        .partial(
            groupers=[{"index_name": "Year"}],
            **(params_dict.get("yearly_groupers") or {}),
        )
        .call()
    )

    quarterly_groupers = (
        set_groupers.validate()
        .set_task_instance_id("quarterly_groupers")
        .handle_errors()
        .with_tracing()
        .partial(
            groupers=[{"index_name": "Quarter"}],
            **(params_dict.get("quarterly_groupers") or {}),
        )
        .call()
    )

    split_yearly = (
        split_groups.validate()
        .set_task_instance_id("split_yearly")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            groupers=yearly_groupers,
            **(params_dict.get("split_yearly") or {}),
        )
        .call()
    )

    split_quarterly = (
        split_groups.validate()
        .set_task_instance_id("split_quarterly")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            groupers=quarterly_groupers,
            **(params_dict.get("split_quarterly") or {}),
        )
        .call()
    )

    tbl_poaching = (
        draw_community_feedback_table.validate()
        .set_task_instance_id("tbl_poaching")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            activity_key="poaching",
            icons_dir=icons_input,
            station_column="Station",
            village_column="Village",
            low_threshold=12,
            high_threshold=30,
            **(params_dict.get("tbl_poaching") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_yearly)
    )

    persist_tbl_poaching = (
        persist_text.validate()
        .set_task_instance_id("persist_tbl_poaching")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="feedback_poaching",
            **(params_dict.get("persist_tbl_poaching") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=tbl_poaching)
    )

    png_tbl_poaching = (
        html_to_png.validate()
        .set_task_instance_id("png_tbl_poaching")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_tbl_poaching") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_tbl_poaching)
    )

    widget_tbl_poaching = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_tbl_poaching")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Feedback: Poaching", **(params_dict.get("widget_tbl_poaching") or {})
        )
        .mapvalues(argnames=["data"], argvalues=persist_tbl_poaching)
    )

    tbl_mangrove = (
        draw_community_feedback_table.validate()
        .set_task_instance_id("tbl_mangrove")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            activity_key="mangrove logging",
            icons_dir=icons_input,
            station_column="Station",
            village_column="Village",
            low_threshold=12,
            high_threshold=30,
            **(params_dict.get("tbl_mangrove") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_yearly)
    )

    persist_tbl_mangrove = (
        persist_text.validate()
        .set_task_instance_id("persist_tbl_mangrove")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="feedback_mangrove",
            **(params_dict.get("persist_tbl_mangrove") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=tbl_mangrove)
    )

    png_tbl_mangrove = (
        html_to_png.validate()
        .set_task_instance_id("png_tbl_mangrove")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_tbl_mangrove") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_tbl_mangrove)
    )

    widget_tbl_mangrove = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_tbl_mangrove")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Feedback: Mangrove Logging",
            **(params_dict.get("widget_tbl_mangrove") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_tbl_mangrove)
    )

    tbl_fishing = (
        draw_community_feedback_table.validate()
        .set_task_instance_id("tbl_fishing")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            activity_key="illegal fishing",
            icons_dir=icons_input,
            station_column="Station",
            village_column="Village",
            low_threshold=12,
            high_threshold=30,
            **(params_dict.get("tbl_fishing") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_yearly)
    )

    persist_tbl_fishing = (
        persist_text.validate()
        .set_task_instance_id("persist_tbl_fishing")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="feedback_fishing",
            **(params_dict.get("persist_tbl_fishing") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=tbl_fishing)
    )

    png_tbl_fishing = (
        html_to_png.validate()
        .set_task_instance_id("png_tbl_fishing")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_tbl_fishing") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_tbl_fishing)
    )

    widget_tbl_fishing = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_tbl_fishing")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Feedback: Illegal Fishing",
            **(params_dict.get("widget_tbl_fishing") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_tbl_fishing)
    )

    tbl_arrests = (
        draw_community_feedback_table.validate()
        .set_task_instance_id("tbl_arrests")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            activity_key="arrests",
            icons_dir=icons_input,
            station_column="Station",
            village_column="Village",
            low_threshold=12,
            high_threshold=30,
            **(params_dict.get("tbl_arrests") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_yearly)
    )

    persist_tbl_arrests = (
        persist_text.validate()
        .set_task_instance_id("persist_tbl_arrests")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="feedback_arrests",
            **(params_dict.get("persist_tbl_arrests") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=tbl_arrests)
    )

    png_tbl_arrests = (
        html_to_png.validate()
        .set_task_instance_id("png_tbl_arrests")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_tbl_arrests") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_tbl_arrests)
    )

    widget_tbl_arrests = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_tbl_arrests")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Feedback: Arrests", **(params_dict.get("widget_tbl_arrests") or {})
        )
        .mapvalues(argnames=["data"], argvalues=persist_tbl_arrests)
    )

    tbl_turtles = (
        draw_community_feedback_table.validate()
        .set_task_instance_id("tbl_turtles")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            activity_key="poached turtle sum",
            icons_dir=icons_input,
            station_column="Station",
            village_column="Village",
            low_threshold=12,
            high_threshold=30,
            **(params_dict.get("tbl_turtles") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_yearly)
    )

    persist_tbl_turtles = (
        persist_text.validate()
        .set_task_instance_id("persist_tbl_turtles")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="feedback_turtles",
            **(params_dict.get("persist_tbl_turtles") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=tbl_turtles)
    )

    png_tbl_turtles = (
        html_to_png.validate()
        .set_task_instance_id("png_tbl_turtles")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_tbl_turtles") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_tbl_turtles)
    )

    widget_tbl_turtles = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_tbl_turtles")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Feedback: Poached Turtles",
            **(params_dict.get("widget_tbl_turtles") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_tbl_turtles)
    )

    monthly_heatmap = (
        draw_monthly_heatmap.validate()
        .set_task_instance_id("monthly_heatmap")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village_column="Village",
            title_prefix="Monthly Distribution of Illegal Events by Village",
            **(params_dict.get("monthly_heatmap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_yearly)
    )

    persist_heatmap = (
        persist_text.validate()
        .set_task_instance_id("persist_heatmap")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="monthly_heatmap",
            **(params_dict.get("persist_heatmap") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=monthly_heatmap)
    )

    png_monthly_heatmap = (
        html_to_png.validate()
        .set_task_instance_id("png_monthly_heatmap")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_monthly_heatmap") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_heatmap)
    )

    widget_heatmap = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_heatmap")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Monthly Illegal Events Heatmap",
            **(params_dict.get("widget_heatmap") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_heatmap)
    )

    donut_v01 = (
        draw_village_donut_chart.validate()
        .set_task_instance_id("donut_v01")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Darakasi to Watamu",
            village_column="Village",
            damaging_col="Damaging coral activity",
            **(params_dict.get("donut_v01") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_yearly)
    )

    persist_donut_v01 = (
        persist_text.validate()
        .set_task_instance_id("persist_donut_v01")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="donut_darakasi_watamu",
            **(params_dict.get("persist_donut_v01") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=donut_v01)
    )

    png_donut_v01 = (
        html_to_png.validate()
        .set_task_instance_id("png_donut_v01")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_donut_v01") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_donut_v01)
    )

    widget_donut_v01 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_donut_v01")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Donut: Darakasi to Watamu",
            **(params_dict.get("widget_donut_v01") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_donut_v01)
    )

    donut_v02 = (
        draw_village_donut_chart.validate()
        .set_task_instance_id("donut_v02")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Dongokundu to Sita",
            village_column="Village",
            damaging_col="Damaging coral activity",
            **(params_dict.get("donut_v02") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_yearly)
    )

    persist_donut_v02 = (
        persist_text.validate()
        .set_task_instance_id("persist_donut_v02")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="donut_dongokundu_sita",
            **(params_dict.get("persist_donut_v02") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=donut_v02)
    )

    png_donut_v02 = (
        html_to_png.validate()
        .set_task_instance_id("png_donut_v02")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_donut_v02") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_donut_v02)
    )

    widget_donut_v02 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_donut_v02")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Donut: Dongokundu to Sita",
            **(params_dict.get("widget_donut_v02") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_donut_v02)
    )

    donut_v03 = (
        draw_village_donut_chart.validate()
        .set_task_instance_id("donut_v03")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Jacaranda to Kanani",
            village_column="Village",
            damaging_col="Damaging coral activity",
            **(params_dict.get("donut_v03") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_yearly)
    )

    persist_donut_v03 = (
        persist_text.validate()
        .set_task_instance_id("persist_donut_v03")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="donut_jacaranda_kanani",
            **(params_dict.get("persist_donut_v03") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=donut_v03)
    )

    png_donut_v03 = (
        html_to_png.validate()
        .set_task_instance_id("png_donut_v03")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_donut_v03") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_donut_v03)
    )

    widget_donut_v03 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_donut_v03")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Donut: Jacaranda to Kanani",
            **(params_dict.get("widget_donut_v03") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_donut_v03)
    )

    donut_v04 = (
        draw_village_donut_chart.validate()
        .set_task_instance_id("donut_v04")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Kanani to Darakasi",
            village_column="Village",
            damaging_col="Damaging coral activity",
            **(params_dict.get("donut_v04") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_yearly)
    )

    persist_donut_v04 = (
        persist_text.validate()
        .set_task_instance_id("persist_donut_v04")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="donut_kanani_darakasi",
            **(params_dict.get("persist_donut_v04") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=donut_v04)
    )

    png_donut_v04 = (
        html_to_png.validate()
        .set_task_instance_id("png_donut_v04")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_donut_v04") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_donut_v04)
    )

    widget_donut_v04 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_donut_v04")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Donut: Kanani to Darakasi",
            **(params_dict.get("widget_donut_v04") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_donut_v04)
    )

    donut_v05 = (
        draw_village_donut_chart.validate()
        .set_task_instance_id("donut_v05")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Kivunjeni to Wesa",
            village_column="Village",
            damaging_col="Damaging coral activity",
            **(params_dict.get("donut_v05") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_yearly)
    )

    persist_donut_v05 = (
        persist_text.validate()
        .set_task_instance_id("persist_donut_v05")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="donut_kivunjeni_wesa",
            **(params_dict.get("persist_donut_v05") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=donut_v05)
    )

    png_donut_v05 = (
        html_to_png.validate()
        .set_task_instance_id("png_donut_v05")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_donut_v05") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_donut_v05)
    )

    widget_donut_v05 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_donut_v05")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Donut: Kivunjeni to Wesa",
            **(params_dict.get("widget_donut_v05") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_donut_v05)
    )

    donut_v06 = (
        draw_village_donut_chart.validate()
        .set_task_instance_id("donut_v06")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Magangani to Mida",
            village_column="Village",
            damaging_col="Damaging coral activity",
            **(params_dict.get("donut_v06") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_yearly)
    )

    persist_donut_v06 = (
        persist_text.validate()
        .set_task_instance_id("persist_donut_v06")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="donut_magangani_mida",
            **(params_dict.get("persist_donut_v06") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=donut_v06)
    )

    png_donut_v06 = (
        html_to_png.validate()
        .set_task_instance_id("png_donut_v06")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_donut_v06") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_donut_v06)
    )

    widget_donut_v06 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_donut_v06")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Donut: Magangani to Mida",
            **(params_dict.get("widget_donut_v06") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_donut_v06)
    )

    donut_v07 = (
        draw_village_donut_chart.validate()
        .set_task_instance_id("donut_v07")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Marafiki to Uyombo",
            village_column="Village",
            damaging_col="Damaging coral activity",
            **(params_dict.get("donut_v07") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_yearly)
    )

    persist_donut_v07 = (
        persist_text.validate()
        .set_task_instance_id("persist_donut_v07")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="donut_marafiki_uyombo",
            **(params_dict.get("persist_donut_v07") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=donut_v07)
    )

    png_donut_v07 = (
        html_to_png.validate()
        .set_task_instance_id("png_donut_v07")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_donut_v07") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_donut_v07)
    )

    widget_donut_v07 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_donut_v07")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Donut: Marafiki to Uyombo",
            **(params_dict.get("widget_donut_v07") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_donut_v07)
    )

    donut_v08 = (
        draw_village_donut_chart.validate()
        .set_task_instance_id("donut_v08")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Mawe Ya Kati to Jacaranda",
            village_column="Village",
            damaging_col="Damaging coral activity",
            **(params_dict.get("donut_v08") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_yearly)
    )

    persist_donut_v08 = (
        persist_text.validate()
        .set_task_instance_id("persist_donut_v08")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="donut_mawe_jacaranda",
            **(params_dict.get("persist_donut_v08") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=donut_v08)
    )

    png_donut_v08 = (
        html_to_png.validate()
        .set_task_instance_id("png_donut_v08")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_donut_v08") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_donut_v08)
    )

    widget_donut_v08 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_donut_v08")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Donut: Mawe Ya Kati to Jacaranda",
            **(params_dict.get("widget_donut_v08") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_donut_v08)
    )

    donut_v09 = (
        draw_village_donut_chart.validate()
        .set_task_instance_id("donut_v09")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Mid Mayungu to Mawe Ya Kati",
            village_column="Village",
            damaging_col="Damaging coral activity",
            **(params_dict.get("donut_v09") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_yearly)
    )

    persist_donut_v09 = (
        persist_text.validate()
        .set_task_instance_id("persist_donut_v09")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="donut_mid_mayungu_mawe",
            **(params_dict.get("persist_donut_v09") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=donut_v09)
    )

    png_donut_v09 = (
        html_to_png.validate()
        .set_task_instance_id("png_donut_v09")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_donut_v09") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_donut_v09)
    )

    widget_donut_v09 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_donut_v09")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Donut: Mid Mayungu to Mawe Ya Kati",
            **(params_dict.get("widget_donut_v09") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_donut_v09)
    )

    donut_v10 = (
        draw_village_donut_chart.validate()
        .set_task_instance_id("donut_v10")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Mida to Marafiki",
            village_column="Village",
            damaging_col="Damaging coral activity",
            **(params_dict.get("donut_v10") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_yearly)
    )

    persist_donut_v10 = (
        persist_text.validate()
        .set_task_instance_id("persist_donut_v10")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="donut_mida_marafiki",
            **(params_dict.get("persist_donut_v10") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=donut_v10)
    )

    png_donut_v10 = (
        html_to_png.validate()
        .set_task_instance_id("png_donut_v10")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_donut_v10") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_donut_v10)
    )

    widget_donut_v10 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_donut_v10")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Donut: Mida to Marafiki",
            **(params_dict.get("widget_donut_v10") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_donut_v10)
    )

    donut_v11 = (
        draw_village_donut_chart.validate()
        .set_task_instance_id("donut_v11")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Sita to Magangani",
            village_column="Village",
            damaging_col="Damaging coral activity",
            **(params_dict.get("donut_v11") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_yearly)
    )

    persist_donut_v11 = (
        persist_text.validate()
        .set_task_instance_id("persist_donut_v11")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="donut_sita_magangani",
            **(params_dict.get("persist_donut_v11") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=donut_v11)
    )

    png_donut_v11 = (
        html_to_png.validate()
        .set_task_instance_id("png_donut_v11")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_donut_v11") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_donut_v11)
    )

    widget_donut_v11 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_donut_v11")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Donut: Sita to Magangani",
            **(params_dict.get("widget_donut_v11") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_donut_v11)
    )

    donut_v12 = (
        draw_village_donut_chart.validate()
        .set_task_instance_id("donut_v12")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Uyombo to Kivunjeni",
            village_column="Village",
            damaging_col="Damaging coral activity",
            **(params_dict.get("donut_v12") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_yearly)
    )

    persist_donut_v12 = (
        persist_text.validate()
        .set_task_instance_id("persist_donut_v12")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="donut_uyombo_kivunjeni",
            **(params_dict.get("persist_donut_v12") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=donut_v12)
    )

    png_donut_v12 = (
        html_to_png.validate()
        .set_task_instance_id("png_donut_v12")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_donut_v12") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_donut_v12)
    )

    widget_donut_v12 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_donut_v12")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Donut: Uyombo to Kivunjeni",
            **(params_dict.get("widget_donut_v12") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_donut_v12)
    )

    donut_v13 = (
        draw_village_donut_chart.validate()
        .set_task_instance_id("donut_v13")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Watamu to Dongokundu",
            village_column="Village",
            damaging_col="Damaging coral activity",
            **(params_dict.get("donut_v13") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_yearly)
    )

    persist_donut_v13 = (
        persist_text.validate()
        .set_task_instance_id("persist_donut_v13")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="donut_watamu_dongokundu",
            **(params_dict.get("persist_donut_v13") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=donut_v13)
    )

    png_donut_v13 = (
        html_to_png.validate()
        .set_task_instance_id("png_donut_v13")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_donut_v13") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_donut_v13)
    )

    widget_donut_v13 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_donut_v13")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Donut: Watamu to Dongokundu",
            **(params_dict.get("widget_donut_v13") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_donut_v13)
    )

    lb_poaching = (
        draw_activity_leaderboard.validate()
        .set_task_instance_id("lb_poaching")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            activity_key="poaching",
            icons_dir=icons_input,
            station_column="Station",
            village_column="Village",
            no_mangrove_sectors=None,
            **(params_dict.get("lb_poaching") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_quarterly)
    )

    persist_lb_poaching = (
        persist_text.validate()
        .set_task_instance_id("persist_lb_poaching")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="lb_poaching",
            **(params_dict.get("persist_lb_poaching") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=lb_poaching)
    )

    png_lb_poaching = (
        html_to_png.validate()
        .set_task_instance_id("png_lb_poaching")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_lb_poaching") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_lb_poaching)
    )

    widget_lb_poaching = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_lb_poaching")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Leaderboard: Poaching",
            **(params_dict.get("widget_lb_poaching") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_lb_poaching)
    )

    lb_mangrove = (
        draw_activity_leaderboard.validate()
        .set_task_instance_id("lb_mangrove")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            activity_key="mangrove logging",
            icons_dir=icons_input,
            station_column="Station",
            village_column="Village",
            no_mangrove_sectors=[
                "Sector 2",
                "Sector 3",
                "Sector 4",
                "Sector 5",
                "Sector 13",
            ],
            **(params_dict.get("lb_mangrove") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_quarterly)
    )

    persist_lb_mangrove = (
        persist_text.validate()
        .set_task_instance_id("persist_lb_mangrove")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="lb_mangrove",
            **(params_dict.get("persist_lb_mangrove") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=lb_mangrove)
    )

    png_lb_mangrove = (
        html_to_png.validate()
        .set_task_instance_id("png_lb_mangrove")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_lb_mangrove") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_lb_mangrove)
    )

    widget_lb_mangrove = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_lb_mangrove")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Leaderboard: Mangrove Logging",
            **(params_dict.get("widget_lb_mangrove") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_lb_mangrove)
    )

    lb_fishing = (
        draw_activity_leaderboard.validate()
        .set_task_instance_id("lb_fishing")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            activity_key="illegal fishing",
            icons_dir=icons_input,
            station_column="Station",
            village_column="Village",
            no_mangrove_sectors=None,
            **(params_dict.get("lb_fishing") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_quarterly)
    )

    persist_lb_fishing = (
        persist_text.validate()
        .set_task_instance_id("persist_lb_fishing")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="lb_fishing",
            **(params_dict.get("persist_lb_fishing") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=lb_fishing)
    )

    png_lb_fishing = (
        html_to_png.validate()
        .set_task_instance_id("png_lb_fishing")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_lb_fishing") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_lb_fishing)
    )

    widget_lb_fishing = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_lb_fishing")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Leaderboard: Illegal Fishing",
            **(params_dict.get("widget_lb_fishing") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_lb_fishing)
    )

    lb_arrests = (
        draw_activity_leaderboard.validate()
        .set_task_instance_id("lb_arrests")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            activity_key="arrests",
            icons_dir=icons_input,
            station_column="Station",
            village_column="Village",
            no_mangrove_sectors=None,
            **(params_dict.get("lb_arrests") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_quarterly)
    )

    persist_lb_arrests = (
        persist_text.validate()
        .set_task_instance_id("persist_lb_arrests")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="lb_arrests",
            **(params_dict.get("persist_lb_arrests") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=lb_arrests)
    )

    png_lb_arrests = (
        html_to_png.validate()
        .set_task_instance_id("png_lb_arrests")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_lb_arrests") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_lb_arrests)
    )

    widget_lb_arrests = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_lb_arrests")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Leaderboard: Arrests", **(params_dict.get("widget_lb_arrests") or {})
        )
        .mapvalues(argnames=["data"], argvalues=persist_lb_arrests)
    )

    ibar_v01 = (
        draw_village_icon_bar.validate()
        .set_task_instance_id("ibar_v01")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Darakasi to Watamu",
            icons_dir=icons_input,
            village_column="Village",
            icons_per_row=8,
            **(params_dict.get("ibar_v01") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_quarterly)
    )

    persist_ibar_v01 = (
        persist_text.validate()
        .set_task_instance_id("persist_ibar_v01")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="ibar_darakasi_watamu",
            **(params_dict.get("persist_ibar_v01") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=ibar_v01)
    )

    png_ibar_v01 = (
        html_to_png.validate()
        .set_task_instance_id("png_ibar_v01")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_ibar_v01") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v01)
    )

    widget_ibar_v01 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_ibar_v01")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Icon Bar: Darakasi to Watamu",
            **(params_dict.get("widget_ibar_v01") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_ibar_v01)
    )

    ibar_v02 = (
        draw_village_icon_bar.validate()
        .set_task_instance_id("ibar_v02")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Dongokundu to Sita",
            icons_dir=icons_input,
            village_column="Village",
            icons_per_row=8,
            **(params_dict.get("ibar_v02") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_quarterly)
    )

    persist_ibar_v02 = (
        persist_text.validate()
        .set_task_instance_id("persist_ibar_v02")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="ibar_dongokundu_sita",
            **(params_dict.get("persist_ibar_v02") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=ibar_v02)
    )

    png_ibar_v02 = (
        html_to_png.validate()
        .set_task_instance_id("png_ibar_v02")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_ibar_v02") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v02)
    )

    widget_ibar_v02 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_ibar_v02")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Icon Bar: Dongokundu to Sita",
            **(params_dict.get("widget_ibar_v02") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_ibar_v02)
    )

    ibar_v03 = (
        draw_village_icon_bar.validate()
        .set_task_instance_id("ibar_v03")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Magangani to Mida",
            icons_dir=icons_input,
            village_column="Village",
            icons_per_row=8,
            **(params_dict.get("ibar_v03") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_quarterly)
    )

    persist_ibar_v03 = (
        persist_text.validate()
        .set_task_instance_id("persist_ibar_v03")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="ibar_magangani_mida",
            **(params_dict.get("persist_ibar_v03") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=ibar_v03)
    )

    png_ibar_v03 = (
        html_to_png.validate()
        .set_task_instance_id("png_ibar_v03")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_ibar_v03") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v03)
    )

    widget_ibar_v03 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_ibar_v03")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Icon Bar: Magangani to Mida",
            **(params_dict.get("widget_ibar_v03") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_ibar_v03)
    )

    ibar_v04 = (
        draw_village_icon_bar.validate()
        .set_task_instance_id("ibar_v04")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Uyombo to Kivunjeni",
            icons_dir=icons_input,
            village_column="Village",
            icons_per_row=8,
            **(params_dict.get("ibar_v04") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_quarterly)
    )

    persist_ibar_v04 = (
        persist_text.validate()
        .set_task_instance_id("persist_ibar_v04")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="ibar_uyombo_kivunjeni",
            **(params_dict.get("persist_ibar_v04") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=ibar_v04)
    )

    png_ibar_v04 = (
        html_to_png.validate()
        .set_task_instance_id("png_ibar_v04")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_ibar_v04") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v04)
    )

    widget_ibar_v04 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_ibar_v04")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Icon Bar: Uyombo to Kivunjeni",
            **(params_dict.get("widget_ibar_v04") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_ibar_v04)
    )

    ibar_v05 = (
        draw_village_icon_bar.validate()
        .set_task_instance_id("ibar_v05")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Watamu to Dongokundu",
            icons_dir=icons_input,
            village_column="Village",
            icons_per_row=8,
            **(params_dict.get("ibar_v05") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_quarterly)
    )

    persist_ibar_v05 = (
        persist_text.validate()
        .set_task_instance_id("persist_ibar_v05")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="ibar_watamu_dongokundu",
            **(params_dict.get("persist_ibar_v05") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=ibar_v05)
    )

    png_ibar_v05 = (
        html_to_png.validate()
        .set_task_instance_id("png_ibar_v05")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_ibar_v05") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v05)
    )

    widget_ibar_v05 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_ibar_v05")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Icon Bar: Watamu to Dongokundu",
            **(params_dict.get("widget_ibar_v05") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_ibar_v05)
    )

    ibar_v06 = (
        draw_village_icon_bar.validate()
        .set_task_instance_id("ibar_v06")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Mida to Marafiki",
            icons_dir=icons_input,
            village_column="Village",
            icons_per_row=8,
            **(params_dict.get("ibar_v06") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_quarterly)
    )

    persist_ibar_v06 = (
        persist_text.validate()
        .set_task_instance_id("persist_ibar_v06")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="ibar_mida_marafiki",
            **(params_dict.get("persist_ibar_v06") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=ibar_v06)
    )

    png_ibar_v06 = (
        html_to_png.validate()
        .set_task_instance_id("png_ibar_v06")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_ibar_v06") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v06)
    )

    widget_ibar_v06 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_ibar_v06")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Icon Bar: Mida to Marafiki",
            **(params_dict.get("widget_ibar_v06") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_ibar_v06)
    )

    ibar_v07 = (
        draw_village_icon_bar.validate()
        .set_task_instance_id("ibar_v07")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Mawe Ya Kati to Jacaranda",
            icons_dir=icons_input,
            village_column="Village",
            icons_per_row=8,
            **(params_dict.get("ibar_v07") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_quarterly)
    )

    persist_ibar_v07 = (
        persist_text.validate()
        .set_task_instance_id("persist_ibar_v07")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="ibar_mawe_jacaranda",
            **(params_dict.get("persist_ibar_v07") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=ibar_v07)
    )

    png_ibar_v07 = (
        html_to_png.validate()
        .set_task_instance_id("png_ibar_v07")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_ibar_v07") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v07)
    )

    widget_ibar_v07 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_ibar_v07")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Icon Bar: Mawe Ya Kati to Jacaranda",
            **(params_dict.get("widget_ibar_v07") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_ibar_v07)
    )

    ibar_v08 = (
        draw_village_icon_bar.validate()
        .set_task_instance_id("ibar_v08")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Mid Mayungu to Mawe Ya Kati",
            icons_dir=icons_input,
            village_column="Village",
            icons_per_row=8,
            **(params_dict.get("ibar_v08") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_quarterly)
    )

    persist_ibar_v08 = (
        persist_text.validate()
        .set_task_instance_id("persist_ibar_v08")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="ibar_mid_mayungu_mawe",
            **(params_dict.get("persist_ibar_v08") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=ibar_v08)
    )

    png_ibar_v08 = (
        html_to_png.validate()
        .set_task_instance_id("png_ibar_v08")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_ibar_v08") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v08)
    )

    widget_ibar_v08 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_ibar_v08")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Icon Bar: Mid Mayungu to Mawe Ya Kati",
            **(params_dict.get("widget_ibar_v08") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_ibar_v08)
    )

    ibar_v09 = (
        draw_village_icon_bar.validate()
        .set_task_instance_id("ibar_v09")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Marafiki to Uyombo",
            icons_dir=icons_input,
            village_column="Village",
            icons_per_row=8,
            **(params_dict.get("ibar_v09") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_quarterly)
    )

    persist_ibar_v09 = (
        persist_text.validate()
        .set_task_instance_id("persist_ibar_v09")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="ibar_marafiki_uyombo",
            **(params_dict.get("persist_ibar_v09") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=ibar_v09)
    )

    png_ibar_v09 = (
        html_to_png.validate()
        .set_task_instance_id("png_ibar_v09")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_ibar_v09") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v09)
    )

    widget_ibar_v09 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_ibar_v09")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Icon Bar: Marafiki to Uyombo",
            **(params_dict.get("widget_ibar_v09") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_ibar_v09)
    )

    ibar_v10 = (
        draw_village_icon_bar.validate()
        .set_task_instance_id("ibar_v10")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Kivunjeni to Wesa",
            icons_dir=icons_input,
            village_column="Village",
            icons_per_row=8,
            **(params_dict.get("ibar_v10") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_quarterly)
    )

    persist_ibar_v10 = (
        persist_text.validate()
        .set_task_instance_id("persist_ibar_v10")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="ibar_kivunjeni_wesa",
            **(params_dict.get("persist_ibar_v10") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=ibar_v10)
    )

    png_ibar_v10 = (
        html_to_png.validate()
        .set_task_instance_id("png_ibar_v10")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_ibar_v10") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v10)
    )

    widget_ibar_v10 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_ibar_v10")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Icon Bar: Kivunjeni to Wesa",
            **(params_dict.get("widget_ibar_v10") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_ibar_v10)
    )

    ibar_v11 = (
        draw_village_icon_bar.validate()
        .set_task_instance_id("ibar_v11")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Kanani to Darakasi",
            icons_dir=icons_input,
            village_column="Village",
            icons_per_row=8,
            **(params_dict.get("ibar_v11") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_quarterly)
    )

    persist_ibar_v11 = (
        persist_text.validate()
        .set_task_instance_id("persist_ibar_v11")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="ibar_kanani_darakasi",
            **(params_dict.get("persist_ibar_v11") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=ibar_v11)
    )

    png_ibar_v11 = (
        html_to_png.validate()
        .set_task_instance_id("png_ibar_v11")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_ibar_v11") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v11)
    )

    widget_ibar_v11 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_ibar_v11")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Icon Bar: Kanani to Darakasi",
            **(params_dict.get("widget_ibar_v11") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_ibar_v11)
    )

    ibar_v12 = (
        draw_village_icon_bar.validate()
        .set_task_instance_id("ibar_v12")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Jacaranda to Kanani",
            icons_dir=icons_input,
            village_column="Village",
            icons_per_row=8,
            **(params_dict.get("ibar_v12") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_quarterly)
    )

    persist_ibar_v12 = (
        persist_text.validate()
        .set_task_instance_id("persist_ibar_v12")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="ibar_jacaranda_kanani",
            **(params_dict.get("persist_ibar_v12") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=ibar_v12)
    )

    png_ibar_v12 = (
        html_to_png.validate()
        .set_task_instance_id("png_ibar_v12")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_ibar_v12") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v12)
    )

    widget_ibar_v12 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_ibar_v12")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Icon Bar: Jacaranda to Kanani",
            **(params_dict.get("widget_ibar_v12") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_ibar_v12)
    )

    ibar_v13 = (
        draw_village_icon_bar.validate()
        .set_task_instance_id("ibar_v13")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            village="Watamu to Dongokundu",
            icons_dir=icons_input,
            village_column="Village",
            icons_per_row=8,
            **(params_dict.get("ibar_v13") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_quarterly)
    )

    persist_ibar_v13 = (
        persist_text.validate()
        .set_task_instance_id("persist_ibar_v13")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="ibar_watamu_dongokundu",
            **(params_dict.get("persist_ibar_v13") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=ibar_v13)
    )

    png_ibar_v13 = (
        html_to_png.validate()
        .set_task_instance_id("png_ibar_v13")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_ibar_v13") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_ibar_v13)
    )

    widget_ibar_v13 = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_ibar_v13")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Icon Bar: Watamu to Dongokundu",
            **(params_dict.get("widget_ibar_v13") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_ibar_v13)
    )

    all_villages_bar = (
        draw_all_villages_icon_bar.validate()
        .set_task_instance_id("all_villages_bar")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            icons_dir=icons_input,
            village_column="Village",
            icons_per_row=8,
            **(params_dict.get("all_villages_bar") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_quarterly)
    )

    persist_all_villages_bar = (
        persist_text.validate()
        .set_task_instance_id("persist_all_villages_bar")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="all_villages_icon_bar",
            **(params_dict.get("persist_all_villages_bar") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=all_villages_bar)
    )

    png_all_villages_bar = (
        html_to_png.validate()
        .set_task_instance_id("png_all_villages_bar")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_all_villages_bar") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_all_villages_bar)
    )

    widget_all_villages_bar = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("widget_all_villages_bar")
        .handle_errors()
        .with_tracing()
        .partial(
            title="All Villages Illegal Events",
            **(params_dict.get("widget_all_villages_bar") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_all_villages_bar)
    )

    split_maps = (
        split_groups.validate()
        .set_task_instance_id("split_maps")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            groupers=yearly_groupers,
            **(params_dict.get("split_maps") or {}),
        )
        .call()
    )

    illegal_events_map = (
        draw_illegal_events_map.validate()
        .set_task_instance_id("illegal_events_map")
        .handle_errors()
        .with_tracing()
        .partial(
            groupers=yearly_groupers,
            marine_layers_path=marine_layers_input,
            widget_id="Illegal Events Map",
            **(params_dict.get("illegal_events_map") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_maps)
    )

    persist_ie_map = (
        persist_text.validate()
        .set_task_instance_id("persist_ie_map")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="illegal_events_map",
            **(params_dict.get("persist_ie_map") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=illegal_events_map)
    )

    png_ie_map = (
        html_to_png.validate()
        .set_task_instance_id("png_ie_map")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_ie_map") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_ie_map)
    )

    widget_ie_map = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("widget_ie_map")
        .handle_errors()
        .with_tracing()
        .partial(title="Illegal Events Map", **(params_dict.get("widget_ie_map") or {}))
        .mapvalues(argnames=["data"], argvalues=persist_ie_map)
    )

    poaching_map = (
        draw_poaching_map.validate()
        .set_task_instance_id("poaching_map")
        .handle_errors()
        .with_tracing()
        .partial(
            groupers=yearly_groupers,
            marine_layers_path=marine_layers_input,
            widget_id="Poaching Hotspot Map",
            **(params_dict.get("poaching_map") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_maps)
    )

    persist_poaching_map = (
        persist_text.validate()
        .set_task_instance_id("persist_poaching_map")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="poaching_map",
            **(params_dict.get("persist_poaching_map") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=poaching_map)
    )

    png_poaching_map = (
        html_to_png.validate()
        .set_task_instance_id("png_poaching_map")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_poaching_map") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_poaching_map)
    )

    widget_poaching_map = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("widget_poaching_map")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Poaching Hotspot Map",
            **(params_dict.get("widget_poaching_map") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_poaching_map)
    )

    mangrove_map = (
        draw_mangrove_logging_map.validate()
        .set_task_instance_id("mangrove_map")
        .handle_errors()
        .with_tracing()
        .partial(
            groupers=yearly_groupers,
            marine_layers_path=marine_layers_input,
            widget_id="Mangrove Logging Map",
            **(params_dict.get("mangrove_map") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_maps)
    )

    persist_mangrove_map = (
        persist_text.validate()
        .set_task_instance_id("persist_mangrove_map")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="mangrove_map",
            **(params_dict.get("persist_mangrove_map") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=mangrove_map)
    )

    png_mangrove_map = (
        html_to_png.validate()
        .set_task_instance_id("png_mangrove_map")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_mangrove_map") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_mangrove_map)
    )

    widget_mangrove_map = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("widget_mangrove_map")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Mangrove Logging Map",
            **(params_dict.get("widget_mangrove_map") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_mangrove_map)
    )

    illegal_fishing_map = (
        draw_illegal_fishing_map.validate()
        .set_task_instance_id("illegal_fishing_map")
        .handle_errors()
        .with_tracing()
        .partial(
            groupers=yearly_groupers,
            marine_layers_path=marine_layers_input,
            widget_id="Illegal Fishing Map",
            **(params_dict.get("illegal_fishing_map") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_maps)
    )

    persist_illegal_fishing_map = (
        persist_text.validate()
        .set_task_instance_id("persist_illegal_fishing_map")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="illegal_fishing_map",
            **(params_dict.get("persist_illegal_fishing_map") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=illegal_fishing_map)
    )

    png_illegal_fishing_map = (
        html_to_png.validate()
        .set_task_instance_id("png_illegal_fishing_map")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_illegal_fishing_map") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_illegal_fishing_map)
    )

    widget_illegal_fishing_map = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("widget_illegal_fishing_map")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Illegal Fishing Map",
            **(params_dict.get("widget_illegal_fishing_map") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_illegal_fishing_map)
    )

    arrests_map = (
        draw_arrests_map.validate()
        .set_task_instance_id("arrests_map")
        .handle_errors()
        .with_tracing()
        .partial(
            groupers=yearly_groupers,
            marine_layers_path=marine_layers_input,
            widget_id="Arrests Map",
            **(params_dict.get("arrests_map") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_maps)
    )

    persist_arrests_map = (
        persist_text.validate()
        .set_task_instance_id("persist_arrests_map")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="arrests_map",
            **(params_dict.get("persist_arrests_map") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=arrests_map)
    )

    png_arrests_map = (
        html_to_png.validate()
        .set_task_instance_id("png_arrests_map")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_arrests_map") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_arrests_map)
    )

    widget_arrests_map = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("widget_arrests_map")
        .handle_errors()
        .with_tracing()
        .partial(title="Arrests Map", **(params_dict.get("widget_arrests_map") or {}))
        .mapvalues(argnames=["data"], argvalues=persist_arrests_map)
    )

    report_year = (
        get_report_year.validate()
        .set_task_instance_id("report_year")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            groupers=yearly_groupers,
            **(params_dict.get("report_year") or {}),
        )
        .call()
    )

    report_generation_date = (
        get_generation_date.validate()
        .set_task_instance_id("report_generation_date")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("report_generation_date") or {}))
        .call()
    )

    render_village_games_report = (
        render_vg_report.validate()
        .set_task_instance_id("render_village_games_report")
        .handle_errors()
        .with_tracing()
        .partial(
            template_path=report_template_input,
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            report_year=report_year,
            generation_date=report_generation_date,
            feedback_poaching_png=png_tbl_poaching,
            feedback_mangrove_png=png_tbl_mangrove,
            feedback_fishing_png=png_tbl_fishing,
            feedback_arrests_png=png_tbl_arrests,
            feedback_turtles_png=png_tbl_turtles,
            monthly_heatmap_png=png_monthly_heatmap,
            donut_darakasi_watamu_png=png_donut_v01,
            donut_dongokundu_sita_png=png_donut_v02,
            donut_jacaranda_kanani_png=png_donut_v03,
            donut_kanani_darakasi_png=png_donut_v04,
            donut_kivunjeni_wesa_png=png_donut_v05,
            donut_magangani_mida_png=png_donut_v06,
            donut_marafiki_uyombo_png=png_donut_v07,
            donut_mawe_jacaranda_png=png_donut_v08,
            donut_mid_mayungu_mawe_png=png_donut_v09,
            donut_mida_marafiki_png=png_donut_v10,
            donut_sita_magangani_png=png_donut_v11,
            donut_uyombo_kivunjeni_png=png_donut_v12,
            donut_watamu_dongokundu_png=png_donut_v13,
            lb_poaching_png=png_lb_poaching,
            lb_mangrove_png=png_lb_mangrove,
            lb_fishing_png=png_lb_fishing,
            lb_arrests_png=png_lb_arrests,
            ibar_darakasi_watamu_png=png_ibar_v01,
            ibar_dongokundu_sita_png=png_ibar_v02,
            ibar_magangani_mida_png=png_ibar_v03,
            ibar_uyombo_kivunjeni_png=png_ibar_v04,
            ibar_watamu_dongokundu_png=png_ibar_v05,
            ibar_mida_marafiki_png=png_ibar_v06,
            ibar_mawe_jacaranda_png=png_ibar_v07,
            ibar_mid_mayungu_mawe_png=png_ibar_v08,
            ibar_marafiki_uyombo_png=png_ibar_v09,
            ibar_kivunjeni_wesa_png=png_ibar_v10,
            ibar_kanani_darakasi_png=png_ibar_v11,
            ibar_jacaranda_kanani_png=png_ibar_v12,
            all_villages_icon_bar_png=png_all_villages_bar,
            illegal_events_map_png=png_ie_map,
            poaching_map_png=png_poaching_map,
            mangrove_map_png=png_mangrove_map,
            illegal_fishing_map_png=png_illegal_fishing_map,
            arrests_map_png=png_arrests_map,
            **(params_dict.get("render_village_games_report") or {}),
        )
        .call()
    )

    grouped_yearly = (
        groupbykey.validate()
        .set_task_instance_id("grouped_yearly")
        .handle_errors()
        .with_tracing()
        .partial(
            iterables=[
                widget_tbl_poaching,
                widget_tbl_mangrove,
                widget_tbl_fishing,
                widget_tbl_arrests,
                widget_tbl_turtles,
                widget_heatmap,
                widget_donut_v01,
                widget_donut_v02,
                widget_donut_v03,
                widget_donut_v04,
                widget_donut_v05,
                widget_donut_v06,
                widget_donut_v07,
                widget_donut_v08,
                widget_donut_v09,
                widget_donut_v10,
                widget_donut_v11,
                widget_donut_v12,
                widget_donut_v13,
                widget_ie_map,
                widget_poaching_map,
                widget_mangrove_map,
                widget_illegal_fishing_map,
                widget_arrests_map,
            ],
            **(params_dict.get("grouped_yearly") or {}),
        )
        .call()
    )

    grouped_quarterly = (
        groupbykey.validate()
        .set_task_instance_id("grouped_quarterly")
        .handle_errors()
        .with_tracing()
        .partial(
            iterables=[
                widget_lb_poaching,
                widget_lb_mangrove,
                widget_lb_fishing,
                widget_lb_arrests,
                widget_ibar_v01,
                widget_ibar_v02,
                widget_ibar_v03,
                widget_ibar_v04,
                widget_ibar_v05,
                widget_ibar_v06,
                widget_ibar_v07,
                widget_ibar_v08,
                widget_ibar_v09,
                widget_ibar_v10,
                widget_ibar_v11,
                widget_ibar_v12,
                widget_ibar_v13,
                widget_all_villages_bar,
            ],
            **(params_dict.get("grouped_quarterly") or {}),
        )
        .call()
    )

    dashboard_widgets = (
        assemble_dashboard_widgets.validate()
        .set_task_instance_id("dashboard_widgets")
        .handle_errors()
        .with_tracing()
        .partial(
            single_view_widgets=[],
            keyed_widgets=grouped_yearly,
            **(params_dict.get("dashboard_widgets") or {}),
        )
        .call()
    )

    vg_dashboard = (
        gather_dashboard.validate()
        .set_task_instance_id("vg_dashboard")
        .handle_errors()
        .with_tracing()
        .partial(
            details=workflow_details,
            groupers=yearly_groupers,
            widgets=dashboard_widgets,
            time_range=time_range,
            **(params_dict.get("vg_dashboard") or {}),
        )
        .call()
    )

    return vg_dashboard
