# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field, conint


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: Optional[str] = Field("", title="Workflow Description")


class CsvInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    retries: Optional[conint(ge=0)] = Field(
        3, description="Number of retries on failure", title="Retries"
    )
    overwrite_existing: Optional[bool] = Field(
        False,
        description="Whether to overwrite existing files",
        title="Overwrite Existing",
    )


class IconsInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    retries: Optional[conint(ge=0)] = Field(
        3, description="Number of retries on failure", title="Retries"
    )
    overwrite_existing: Optional[bool] = Field(
        False,
        description="Whether to overwrite existing files",
        title="Overwrite Existing",
    )


class MarineLayersInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    retries: Optional[conint(ge=0)] = Field(
        3, description="Number of retries on failure", title="Retries"
    )
    overwrite_existing: Optional[bool] = Field(
        False,
        description="Whether to overwrite existing files",
        title="Overwrite Existing",
    )


class ReportTemplateInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    retries: Optional[conint(ge=0)] = Field(
        3, description="Number of retries on failure", title="Retries"
    )
    overwrite_existing: Optional[bool] = Field(
        False,
        description="Whether to overwrite existing files",
        title="Overwrite Existing",
    )


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")
    time_format: Optional[str] = Field(
        "%d %b %Y %H:%M:%S", description="The time format", title="Time Format"
    )


class FormData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: Optional[WorkflowDetails] = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Workflow Details",
    )
    time_range: Optional[TimeRange] = Field(
        None, description="Choose the period of time to analyze.", title="Time Range"
    )
    csv_input: Optional[CsvInput] = Field(None, title="CSV input")
    icons_input: Optional[IconsInput] = Field(None, title="Icons directory")
    marine_layers_input: Optional[MarineLayersInput] = Field(
        None, title="Marine layers path"
    )
    report_template_input: Optional[ReportTemplateInput] = Field(
        None, title="Report template"
    )
