# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from typing import List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field


class WfDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: Optional[str] = Field("", title="Workflow Description")


class LoadData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    layer: Optional[str] = Field(
        None,
        description="Layer name for GeoPackage files (optional, only used for .gpkg files)",
        title="Layer",
    )


class TblPoaching(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    low_threshold: Optional[int] = Field(
        12, description="Events ≤ this → orange circle", title="Low Threshold"
    )
    high_threshold: Optional[int] = Field(
        30, description="Events ≤ this → green circle", title="High Threshold"
    )


class TblMangrove(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    low_threshold: Optional[int] = Field(
        12, description="Events ≤ this → orange circle", title="Low Threshold"
    )
    high_threshold: Optional[int] = Field(
        30, description="Events ≤ this → green circle", title="High Threshold"
    )


class TblFishing(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    low_threshold: Optional[int] = Field(
        12, description="Events ≤ this → orange circle", title="Low Threshold"
    )
    high_threshold: Optional[int] = Field(
        30, description="Events ≤ this → green circle", title="High Threshold"
    )


class TblArrests(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    low_threshold: Optional[int] = Field(
        12, description="Events ≤ this → orange circle", title="Low Threshold"
    )
    high_threshold: Optional[int] = Field(
        30, description="Events ≤ this → green circle", title="High Threshold"
    )


class TblTurtles(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    low_threshold: Optional[int] = Field(
        12, description="Events ≤ this → orange circle", title="Low Threshold"
    )
    high_threshold: Optional[int] = Field(
        30, description="Events ≤ this → green circle", title="High Threshold"
    )


class MonthlyHeatmap(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title_prefix: Optional[str] = Field(
        "Monthly Distribution of Illegal Events by Village",
        description="Chart title prefix",
        title="Title Prefix",
    )


class DonutV01(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    damaging_col: Optional[str] = Field(
        "Damaging coral activity",
        description="Column for damaging coral activity",
        title="Damaging Col",
    )


class DonutV02(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    damaging_col: Optional[str] = Field(
        "Damaging coral activity",
        description="Column for damaging coral activity",
        title="Damaging Col",
    )


class DonutV03(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    damaging_col: Optional[str] = Field(
        "Damaging coral activity",
        description="Column for damaging coral activity",
        title="Damaging Col",
    )


class DonutV04(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    damaging_col: Optional[str] = Field(
        "Damaging coral activity",
        description="Column for damaging coral activity",
        title="Damaging Col",
    )


class DonutV05(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    damaging_col: Optional[str] = Field(
        "Damaging coral activity",
        description="Column for damaging coral activity",
        title="Damaging Col",
    )


class DonutV06(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    damaging_col: Optional[str] = Field(
        "Damaging coral activity",
        description="Column for damaging coral activity",
        title="Damaging Col",
    )


class DonutV07(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    damaging_col: Optional[str] = Field(
        "Damaging coral activity",
        description="Column for damaging coral activity",
        title="Damaging Col",
    )


class DonutV08(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    damaging_col: Optional[str] = Field(
        "Damaging coral activity",
        description="Column for damaging coral activity",
        title="Damaging Col",
    )


class DonutV09(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    damaging_col: Optional[str] = Field(
        "Damaging coral activity",
        description="Column for damaging coral activity",
        title="Damaging Col",
    )


class DonutV10(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    damaging_col: Optional[str] = Field(
        "Damaging coral activity",
        description="Column for damaging coral activity",
        title="Damaging Col",
    )


class DonutV11(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    damaging_col: Optional[str] = Field(
        "Damaging coral activity",
        description="Column for damaging coral activity",
        title="Damaging Col",
    )


class DonutV12(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    damaging_col: Optional[str] = Field(
        "Damaging coral activity",
        description="Column for damaging coral activity",
        title="Damaging Col",
    )


class DonutV13(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    damaging_col: Optional[str] = Field(
        "Damaging coral activity",
        description="Column for damaging coral activity",
        title="Damaging Col",
    )


class LbPoaching(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    no_mangrove_sectors: Optional[List[str]] = Field(
        None,
        description="Sectors with no mangroves (mangrove logging only)",
        title="No Mangrove Sectors",
    )


class LbFishing(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    no_mangrove_sectors: Optional[List[str]] = Field(
        None,
        description="Sectors with no mangroves (mangrove logging only)",
        title="No Mangrove Sectors",
    )


class LbArrests(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    no_mangrove_sectors: Optional[List[str]] = Field(
        None,
        description="Sectors with no mangroves (mangrove logging only)",
        title="No Mangrove Sectors",
    )


class IbarV01(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    icons_per_row: Optional[int] = Field(
        8, description="Icons per row before wrapping", title="Icons Per Row"
    )


class IbarV02(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    icons_per_row: Optional[int] = Field(
        8, description="Icons per row before wrapping", title="Icons Per Row"
    )


class IbarV03(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    icons_per_row: Optional[int] = Field(
        8, description="Icons per row before wrapping", title="Icons Per Row"
    )


class IbarV04(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    icons_per_row: Optional[int] = Field(
        8, description="Icons per row before wrapping", title="Icons Per Row"
    )


class IbarV05(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    icons_per_row: Optional[int] = Field(
        8, description="Icons per row before wrapping", title="Icons Per Row"
    )


class IbarV06(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    icons_per_row: Optional[int] = Field(
        8, description="Icons per row before wrapping", title="Icons Per Row"
    )


class IbarV07(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    icons_per_row: Optional[int] = Field(
        8, description="Icons per row before wrapping", title="Icons Per Row"
    )


class IbarV08(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    icons_per_row: Optional[int] = Field(
        8, description="Icons per row before wrapping", title="Icons Per Row"
    )


class IbarV09(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    icons_per_row: Optional[int] = Field(
        8, description="Icons per row before wrapping", title="Icons Per Row"
    )


class IbarV10(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    icons_per_row: Optional[int] = Field(
        8, description="Icons per row before wrapping", title="Icons Per Row"
    )


class IbarV11(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    icons_per_row: Optional[int] = Field(
        8, description="Icons per row before wrapping", title="Icons Per Row"
    )


class IbarV12(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    icons_per_row: Optional[int] = Field(
        8, description="Icons per row before wrapping", title="Icons Per Row"
    )


class IbarV13(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    icons_per_row: Optional[int] = Field(
        8, description="Icons per row before wrapping", title="Icons Per Row"
    )


class AllVillagesBar(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    icons_per_row: Optional[int] = Field(
        8, description="Icons per row before wrapping", title="Icons Per Row"
    )


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class DownloadFile(BaseModel):
    url: str = Field(..., description="URL to download a file", title="URL")


class LocalFile(BaseModel):
    file_path: str = Field(
        ..., description="Path to a local file", title="Local file path"
    )


class TimeRange(BaseModel):
    since: datetime = Field(..., title="Since")
    until: datetime = Field(..., title="Until")
    timezone: TimezoneInfo
    time_format: Optional[str] = Field("%d %b %Y %H:%M:%S", title="Time Format")


class TimeRangeModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")
    time_format: Optional[str] = Field(
        "%d %b %Y %H:%M:%S", description="The time format", title="Time Format"
    )


class CsvInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    input_method: Union[DownloadFile, LocalFile] = Field(..., title="Input Method")


class IconsInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    input_method: Union[DownloadFile, LocalFile] = Field(..., title="Input Method")


class MarineLayersInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    input_method: Union[DownloadFile, LocalFile] = Field(..., title="Input Method")


class ReportTemplateInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    input_method: Union[DownloadFile, LocalFile] = Field(..., title="Input Method")


class VgDashboard(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    time_range: Optional[TimeRange] = Field(
        None, description="Time range filter", title="Time Range"
    )


class Params(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    wf_details: Optional[WfDetails] = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Workflow Details",
    )
    time_range: Optional[TimeRangeModel] = Field(
        None, description="Choose the period of time to analyze.", title="Time Range"
    )
    csv_input: Optional[CsvInput] = Field(None, title="CSV input")
    load_data: Optional[LoadData] = Field(None, title="Load data")
    icons_input: Optional[IconsInput] = Field(None, title="Icons directory")
    marine_layers_input: Optional[MarineLayersInput] = Field(
        None, title="Marine layers path"
    )
    report_template_input: Optional[ReportTemplateInput] = Field(
        None, title="Report template"
    )
    tbl_poaching: Optional[TblPoaching] = Field(None, title="Feedback table - poaching")
    tbl_mangrove: Optional[TblMangrove] = Field(None, title="Feedback table - mangrove")
    tbl_fishing: Optional[TblFishing] = Field(None, title="Feedback table - fishing")
    tbl_arrests: Optional[TblArrests] = Field(None, title="Feedback table - arrests")
    tbl_turtles: Optional[TblTurtles] = Field(None, title="Feedback table - turtles")
    monthly_heatmap: Optional[MonthlyHeatmap] = Field(None, title="Monthly heatmap")
    donut_v01: Optional[DonutV01] = Field(None, title="Donut - Darakasi to Watamu")
    donut_v02: Optional[DonutV02] = Field(None, title="Donut - Dongokundu to Sita")
    donut_v03: Optional[DonutV03] = Field(None, title="Donut - Jacaranda to Kanani")
    donut_v04: Optional[DonutV04] = Field(None, title="Donut - Kanani to Darakasi")
    donut_v05: Optional[DonutV05] = Field(None, title="Donut - Kivunjeni to Wesa")
    donut_v06: Optional[DonutV06] = Field(None, title="Donut - Magangani to Mida")
    donut_v07: Optional[DonutV07] = Field(None, title="Donut - Marafiki to Uyombo")
    donut_v08: Optional[DonutV08] = Field(
        None, title="Donut - Mawe Ya Kati to Jacaranda"
    )
    donut_v09: Optional[DonutV09] = Field(
        None, title="Donut - Mid Mayungu to Mawe Ya Kati"
    )
    donut_v10: Optional[DonutV10] = Field(None, title="Donut - Mida to Marafiki")
    donut_v11: Optional[DonutV11] = Field(None, title="Donut - Sita to Magangani")
    donut_v12: Optional[DonutV12] = Field(None, title="Donut - Uyombo to Kivunjeni")
    donut_v13: Optional[DonutV13] = Field(None, title="Donut - Watamu to Dongokundu")
    lb_poaching: Optional[LbPoaching] = Field(None, title="Leaderboard - poaching")
    lb_fishing: Optional[LbFishing] = Field(None, title="Leaderboard - fishing")
    lb_arrests: Optional[LbArrests] = Field(None, title="Leaderboard - arrests")
    ibar_v01: Optional[IbarV01] = Field(None, title="Icon bar - Darakasi to Watamu")
    ibar_v02: Optional[IbarV02] = Field(None, title="Icon bar - Dongokundu to Sita")
    ibar_v03: Optional[IbarV03] = Field(None, title="Icon bar - Magangani to Mida")
    ibar_v04: Optional[IbarV04] = Field(None, title="Icon bar - Uyombo to Kivunjeni")
    ibar_v05: Optional[IbarV05] = Field(None, title="Icon bar - Watamu to Dongokundu")
    ibar_v06: Optional[IbarV06] = Field(None, title="Icon bar - Mida to Marafiki")
    ibar_v07: Optional[IbarV07] = Field(
        None, title="Icon bar - Mawe Ya Kati to Jacaranda"
    )
    ibar_v08: Optional[IbarV08] = Field(
        None, title="Icon bar - Mid Mayungu to Mawe Ya Kati"
    )
    ibar_v09: Optional[IbarV09] = Field(None, title="Icon bar - Marafiki to Uyombo")
    ibar_v10: Optional[IbarV10] = Field(None, title="Icon bar - Kivunjeni to Wesa")
    ibar_v11: Optional[IbarV11] = Field(None, title="Icon bar - Kanani to Darakasi")
    ibar_v12: Optional[IbarV12] = Field(None, title="Icon bar - Jacaranda to Kanani")
    ibar_v13: Optional[IbarV13] = Field(None, title="Icon bar - Watamu to Dongokundu")
    all_villages_bar: Optional[AllVillagesBar] = Field(
        None, title="All-villages icon bar"
    )
    vg_dashboard: Optional[VgDashboard] = Field(None, title="Village Games Dashboard")
